import fs from 'fs';
import path from 'path';

const handler = async (m, { conn, reply }) => {
  const truths = [
    "Qual è la cosa più imbarazzante che ti sia successa a scuola?",
    "Hai mai rubato qualcosa?",
    "Qual è il tuo più grande rimpianto?",
    "Hai mai fatto finta di essere malato per saltare scuola?",
    "Qual è la bugia più grande che hai detto ai tuoi genitori?",
    "Hai mai spiato qualcuno?",
    "Qual è il segreto che non hai mai detto a nessuno?",
    "Hai mai tradito la fiducia di qualcuno?",
    "Qual è la cosa più strana che hai mangiato?",
    "Hai mai avuto un incidente imbarazzante in pubblico?",
    // Aggiunte 100 nuove domande
    "Hai mai pianto durante un film? Quale?",
    "Qual è la cosa più infantile che fai ancora?",
    "Hai mai avuto un nickname imbarazzante?",
    "Qual è la cosa più folle che faresti per 1 milione di euro?",
    "Hai mai avuto un sogno romantico su qualcuno che conosci?",
    "Qual è la tua più grande insicurezza?",
    "Hai mai invidiato il rapporto di un amico con i suoi genitori?",
    "Qual è la cosa più egoista che hai mai fatto?",
    "Hai mai mentito per sembrare più interessante?",
    "Qual è il tuo più brutto vizio?",
    "Hai mai rubato qualcosa a un amico?",
    "Qual è la cosa più strana che trovi attraente?",
    "Hai mai tradito un segreto?",
    "Qual è la cosa più imbarazzante che hai fatto per attirare l'attenzione?",
    "Hai mai avuto una cotta per un insegnante?",
    "Qual è la cosa più pericolosa che hai mai fatto?",
    "Hai mai fatto qualcosa di illegale?",
    "Qual è la cosa più stupida che hai fatto per amore?",
    "Hai mai inviato un messaggio alla persona sbagliata?",
    "Qual è la tua più grande paura riguardo al futuro?",
    "Hai mai fatto il bagno con i vestiti addosso?",
    "Qual è la cosa più strana che hai fatto da solo/a?",
    "Hai mai avuto paura di essere licenziato?",
    "Qual è il lavoro più strano che hai mai avuto?",
    "Hai mai avuto un incidente imbarazzante con il cibo?",
    "Qual è la cosa più strana che hai fatto per soldi?",
    "Hai mai avuto un'esperienza paranormale?",
    "Qual è la cosa più imbarazzante che i tuoi genitori hanno fatto?",
    "Hai mai mentito sul tuo conto in bancario?",
    "Qual è la cosa più strana che hai fatto per attirare l'attenzione?",
    "Hai mai avuto un incidente imbarazzante in palestra?",
    "Qual è la cosa più strana che hai fatto per sembrare cool?",
    "Hai mai avuto un incidente imbarazzante in piscina?",
    "Qual è la cosa più strana che hai fatto per vincere una scommessa?",
    "Hai mai avuto un incidente imbarazzante in un ristorante?",
    "Qual è la cosa più strana che hai fatto per evitare di lavorare?",
    "Hai mai avuto un incidente imbarazzante in un aeroporto?",
    "Qual è la cosa più strana che hai fatto per evitare di pagare?",
    "Hai mai avuto un incidente imbarazzante in un hotel?",
    "Qual è la cosa più strana che hai fatto per evitare di uscire?",
    "Hai mai avuto un incidente imbarazzante in un centro commerciale?",
    "Qual è la cosa più strana che hai fatto per evitare di parlare con qualcuno?",
    "Hai mai avuto un incidente imbarazzante in spiaggia?",
    "Qual è la cosa più strana che hai fatto per evitare di andare a scuola?",
    "Hai mai avuto un incidente imbarazzante in biblioteca?",
    "Qual è la cosa più strana che hai fatto per evitare di fare i compiti?",
    "Hai mai avuto un incidente imbarazzante in metropolitana?",
    "Qual è la cosa più strana che hai fatto per evitare di incontrare qualcuno?",
    "Hai mai avuto un incidente imbarazzante in un parco?",
    "Qual è la cosa più strana che hai fatto per evitare di rispondere al telefono?",
    "Hai mai avuto un incidente imbarazzante in un bar?",
    "Qual è la cosa più strana che hai fatto per evitare di partecipare a un evento?",
    "Hai mai avuto un incidente imbarazzante in un cinema?",
    "Qual è la cosa più strana che hai fatto per evitare di fare la doccia?",
    "Hai mai avuto un incidente imbarazzante in un museo?",
    "Qual è la cosa più strana che hai fatto per evitare di mangiare qualcosa?",
    "Hai mai avuto un incidente imbarazzante in un ospedale?",
    "Qual è la cosa più strana che hai fatto per evitare di fare esercizio?",
    "Hai mai avuto un incidente imbarazzante in una chiesa?",
    "Qual è la cosa più strana che hai fatto per evitare di pulire?",
    "Hai mai avuto un incidente imbarazzante in un parco divertimenti?",
    "Qual è la cosa più strana che hai fatto per evitare di andare dal dottore?",
    "Hai mai avuto un incidente imbarazzante in una stazione di servizio?",
    "Qual è la cosa più strana che hai fatto per evitare di andare in bagno?",
    "Hai mai avuto un incidente imbarazzante in un negozio?",
    "Qual è la cosa più strana che hai fatto per evitare di parlare in pubblico?",
    "Hai mai avuto un incidente imbarazzante in un autobus?",
    "Qual è la cosa più strana che hai fatto per evitare di guardare qualcosa?",
    "Hai mai avuto un incidente imbarazzante in un taxi?",
    "Qual è la cosa più strana che hai fatto per evitare di ascoltare qualcosa?",
    "Hai mai avuto un incidente imbarazzante in un treno?",
    "Qual è la cosa più strana che hai fatto per evitare di annusare qualcosa?",
    "Hai mai avuto un incidente imbarazzante in un aereo?",
    "Qual è la cosa più strana che hai fatto per evitare di toccare qualcosa?",
    "Hai mai avuto un incidente imbarazzante in un ristorante fast food?",
    "Qual è la cosa più strana che hai fatto per evitare di assaggiare qualcosa?",
    "Hai mai avuto un incidente imbarazzante in un supermercato?",
    "Qual è la cosa più strana che hai fatto per evitare di indossare qualcosa?",
    "Hai mai avuto un incidente imbarazzante in un negozio di abbigliamento?",
    "Qual è la cosa più strana che hai fatto per evitare di comprare qualcosa?",
    "Hai mai avuto un incidente imbarazzante in un negozio di elettronica?",
    "Qual è la cosa più strana che hai fatto per evitare di vendere qualcosa?",
    "Hai mai avuto un incidente imbarazzante in un negozio di animali?",
    "Qual è la cosa più strana che hai fatto per evitare di adottare un animale?",
    "Hai mai avuto un incidente imbarazzante in un negozio di giocattoli?",
    "Qual è la cosa più strana che hai fatto per evitare di giocare con qualcosa?",
    "Hai mai avuto un incidente imbarazzante in un negozio di libri?",
    "Qual è la cosa più strana che hai fatto per evitare di leggere qualcosa?",
    "Hai mai avuto un incidente imbarazzante in un negozio di musica?",
    "Qual è la cosa più strana che hai fatto per evitare di ascoltare musica?",
    "Hai mai avuto un incidente imbarazzante in un negozio di videogiochi?",
    "Qual è la cosa più strana che hai fatto per evitare di giocare a un videogioco?",
    "Hai mai avuto un incidente imbarazzante in un negozio di sport?",
    "Qual è la cosa più strana che hai fatto per evitare di fare sport?",
    "Hai mai avuto un incidente imbarazzante in un negozio di bellezza?",
    "Qual è la cosa più strana che hai fatto per evitare di truccarti?",
    "Hai mai avuto un incidente imbarazzante in un negozio di scarpe?",
    "Qual è la cosa più strana che hai fatto per evitare di indossare scarpe?",
    "Hai mai avuto un incidente imbarazzante in un negozio di gioielli?",
    "Qual è la cosa più strana che hai fatto per evitare di indossare gioielli?",
    "Hai mai avuto un incidente imbarazzante in un negozio di mobili?",
    "Qual è la cosa più strana che hai fatto per evitare di sederti?",
    "Hai mai avuto un incidente imbarazzante in un negozio di fiori?",
    "Qual è la cosa più strana che hai fatto per evitare di annusare fiori?",
    "Hai mai avuto un incidente imbarazzante in un negozio di dolci?",
    "Qual è la cosa più strana che hai fatto per evitare di mangiare dolci?",
        "Se dovessi confessare un crimine che hai commesso ma per cui non sei mai stato scoperto, quale sarebbe?",
    "Qual è la fantasia più strana che hai mai avuto su qualcuno che conosci nella vita reale?",
    "Hai mai provato gelosia così intensa da fare qualcosa di cui ti vergogni ancora?",
    "Qual è il momento in cui ti sei sentito più vulnerabile davanti a qualcuno?",
    "Se potessi leggere la mente di una persona per un giorno, chi sceglieresti e perché?",
    "Qual è la cosa più crudele che hai mai detto a qualcuno intenzionalmente?",
    "Hai mai avuto pensieri romantici su qualcuno in una relazione impegnata?",
    "Qual è il momento in cui hai sentito di aver deluso di più te stesso?",
    "Se dovessi ammettere una dipendenza segreta, quale sarebbe?",
    "Qual è la cosa più immorale che hai mai fatto per ottenere quello che volevi?",
    "Hai mai provato attrazione per qualcuno che avresti dovuto considerare off-limits?",
    "Qual è il pensiero più egoista che ti passa per la testa regolarmente?",
    "Se potessi rubare un talento a qualcuno che conosci, quale sceglieresti?",
    "Qual è la cosa più infantile che fai quando sei completamente solo?",
    "Hai mai mentito su qualcosa di importante durante un colloquio di lavoro?",
    "Qual è il momento in cui ti sei sentito più falso con te stesso?",
    "Se dovessi ammettere di aver sabotato qualcuno, di cosa si tratterebbe?",
    "Qual è la cosa più strana che fai quando pensi che nessuno ti stia guardando?",
    "Hai mai avuto un sogno erotico su qualcuno di totalmente inappropriato?",
    "Qual è la bugia più grossa che hai detto su te stesso per sembrare più interessante?",
    "Se potessi cancellare una relazione dal tuo passato, quale sarebbe?",
    "Qual è il momento in cui hai provato più invidia nella tua vita?",
    "Hai mai fatto qualcosa di illegale che, se scoperto, rovinerebbe la tua reputazione?",
    "Qual è il segreto più imbarazzante che conosci su un membro della tua famiglia?",
    "Se dovessi confessare un tradimento (di qualsiasi tipo), quale sarebbe?",
    "Qual è la cosa più ipocrita che fai regolarmente?",
    "Hai mai desiderato che qualcuno sparisse completamente dalla tua vita?",
    "Qual è il momento in cui ti sei comportato in modo più codardo?",
    "Se potessi spiare la vita privata di chiunque per una settimana, chi sceglieresti?",
    "Qual è la cosa più meschina che hai fatto per vendetta?",
    "Hai mai provato attrazione fisica per qualcuno mentre eri in una relazione?",
    "Qual è il pregiudizio più brutto che hai ma non ammetteresti mai pubblicamente?",
    "Se dovessi ammettere di aver fatto del male a qualcuno intenzionalmente, cosa diresti?",
    "Qual è la cosa più disperata che hai fatto per ottenere attenzione?",
    "Hai mai rubato qualcosa di significativo e non restituito?",
    "Qual è il momento in cui ti sei sentito più solo al mondo?",
    "Se potessi rivivere un momento imbarazzante per cambiarlo, quale sceglieresti?",
    "Qual è la cosa più sciocca per cui hai pianto da adulto?",
    "Hai mai fatto finta di provare sentimenti che non avevi?",
    "Qual è la cosa più strana che ti eccita mentalmente?",
    "Se dovessi ammettere una paura irrazionale che influenza la tua vita, quale sarebbe?",
    "Qual è il momento in cui hai mentito più spudoratamente guardando qualcuno negli occhi?",
    "Hai mai avuto pensieri di vendetta elaborati contro qualcuno?",
    "Qual è la cosa più imbarazzante che hai fatto per denaro?",
    "Se potessi controllare i pensieri di qualcuno per un'ora, cosa gli faresti pensare?",
    "Qual è il segreto più grave che qualcuno ti ha confidato e che hai tradito?",
    "Hai mai fatto qualcosa di sessualmente imbarazzante che nessuno sa?",
    "Qual è la cosa più crudele che hai pensato ma non detto durante un litigio?",
    "Se dovessi ammettere di aver manipolato qualcuno, come l'hai fatto?",
    "Qual è il momento in cui ti sei sentito più sporco moralmente?",
    "Hai mai avuto fantasie di potere assoluto su altre persone?",
    "Qual è la cosa più vigliacca che hai fatto per evitare una responsabilità?",
    "Se potessi far innamorare perdutamente qualcuno di te, chi sceglieresti?",
    "Qual è il pensiero più dark che hai avuto durante un momento felice?",
    "Hai mai desiderato intensamente la vita di qualcun altro al punto da odiarli?",
    "Qual è la cosa più disgustosa che hai fatto e nascosto agli altri?",
    "Se dovessi confessare un momento di estrema debolezza, quale sarebbe?",
    "Qual è la cosa più sleale che hai fatto in una competizione?",
    "Hai mai provato piacere nel vedere qualcuno soffrire?",
    "Qual è il momento in cui ti sei sentito più falso con un amico?",
    "Se potessi eliminare una persona dal passato di qualcun altro, chi elimineresti?",
    "Qual è la cosa più egoista che hai fatto a spese di chi ti ama?",
    "Hai mai mentito su qualcosa di fondamentale della tua personalità?",
    "Qual è il momento in cui hai provato più vergogna per i tuoi pensieri?",
    "Se dovessi ammettere di aver danneggiato intenzionalmente qualcuno emotivamente, cosa diresti?",
    "Qual è la cosa più patetica che hai fatto per ottenere l'approvazione di qualcuno?",
    "Hai mai avuto pensieri ossessivi su qualcuno che ti spaventano?",
    "Qual è il segreto più torbido della tua famiglia che conosci?",
    "Se potessi scambiare la vita con qualcuno per un mese, chi sceglieresti?",
    "Qual è la cosa più immorale che hai fatto e giustificato a te stesso?",
    "Hai mai provato eccitazione in una situazione completamente inappropriata?",
    "Qual è il momento in cui hai tradito i tuoi valori più profondi?",
    "Se dovessi confessare il tuo più grande fallimento come persona, quale sarebbe?",
    "Qual è la cosa più strana che hai fatto quando eri disperatamente solo?",
    "Hai mai desiderato che qualcuno provasse lo stesso dolore che ti ha causato?",
    "Qual è il pensiero più perverso che hai avuto in chiesa o in un luogo sacro?",
    "Se potessi sapere quando morirai, vorresti saperlo davvero?",
    "Qual è la cosa più crudele che hai detto a te stesso?",
    "Hai mai provato attrazione per qualcuno durante un momento di lutto?",
    "Qual è il momento in cui ti sei odiato di più?",
    "Se dovessi ammettere di aver rovinato intenzionalmente qualcosa per qualcuno, cosa sarebbe?",
    "Qual è la fantasia più disturbante che hai mai avuto?",
    "Hai mai mentito su qualcosa di tragico per ottenere compassione?",
    "Qual è la cosa più disumana che hai pensato di fare a qualcuno?",
    "Se potessi cancellare un errore che hai fatto, quale sceglieresti sapendo che cambierebbe tutto?",
    "Qual è il momento in cui ti sei comportato come la persona che giuravi di non diventare mai?",
    "Hai mai provato gelosia così forte da desiderare il male di qualcuno?",
    "Qual è la cosa più vile che hai fatto quando eri arrabbiato?",
    "Se dovessi ammettere di aver tradito la fiducia di qualcuno che ti amava incondizionatamente, cosa diresti?",
    "Qual è il pensiero più egoista che hai durante i momenti difficili degli altri?",
    "Hai mai fatto qualcosa di sessualmente inappropriato che potrebbe distruggere una relazione?",
    "Qual è la cosa più codarda che hai fatto per evitare di ferire qualcuno?",
    "Se potessi far soffrire una persona senza conseguenze, chi sceglieresti?",
    "Qual è il momento in cui hai mentito sapendo che avrebbe fatto molto male a qualcuno?",
    "Hai mai avuto pensieri suicidi che non hai mai condiviso?",
    "Qual è la cosa più sleale che hai fatto per ottenere un vantaggio?",
    "Se dovessi confessare il tuo più grande rimpianto sessuale, quale sarebbe?",
    "Qual è la cosa più meschina che hai fatto per vendetta sociale?",
    "Hai mai desiderato intensamente di essere qualcun altro per sfuggire alla tua vita?",
    "Qual è il segreto più vergognoso che nasconde la tua famiglia?",
    "Se potessi rubare un ricordo felice da qualcuno, lo faresti?",
    "Qual è la cosa più disgustosa che hai fatto per curiosità sessuale?",
    "Hai mai provato eccitazione guardando qualcuno soffrire emotivamente?",
    "Qual è il momento in cui hai realizzato di essere una persona peggiore di quanto pensassi?",
    "Se dovessi ammettere di aver manipolato emotivamente qualcuno, come l'hai fatto?",
    "Qual è la cosa più patologica che fai quando sei completamente solo?",
    "Hai mai avuto fantasie di controllo totale su qualcuno che ami?",
    "Qual è la bugia più elaborata che hai costruito per nascondere chi sei veramente?",
    "Se potessi far dimenticare a qualcuno un momento felice con te, lo faresti per ferirlo?",
    "Qual è la cosa più spregevole che hai pensato durante un momento intimo?",
    "Hai mai desiderato che qualcuno morisse per semplificare la tua vita?",
    "Qual è il momento in cui hai provato più disgusto per te stesso?",
    "Se dovessi confessare la cosa più egoista che fai quotidianamente, quale sarebbe?",
    "Qual è la fantasia più disturbante che hai su qualcuno della tua vita reale?",
    "Hai mai fatto qualcosa di illegale che, se scoperto, cambierebbe come tutti ti vedono?",
    "Qual è la cosa più crudele che hai fatto a un animale?",
    "Se potessi scambiare i problemi della tua vita con quelli di qualcun altro, lo faresti?",
    "Qual è il pensiero più oscuro che hai avuto su un membro della tua famiglia?",
    "Hai mai provato piacere nel rovinare qualcosa di importante per qualcuno?",
    "Qual è la cosa più ipocrita che predichi ma non pratichi?",
    "Se dovessi ammettere di aver mentito su qualcosa di fondamentale di te stesso, cosa sarebbe?",
    "Qual è il momento in cui hai tradito qualcuno che si fidava ciecamente di te?",
    "Hai mai avuto pensieri romantici inappropriati durante un evento triste?",
    "Qual è la cosa più vile che hai fatto per gelosia?",
    "Se potessi far provare a qualcuno il dolore più grande della tua vita, chi sceglieresti?",
    "Qual è la cosa più disgustosa che hai fatto per denaro o vantaggio?",
    "Hai mai mentito su qualcosa di traumatico per ottenere quello che volevi?",
    "Qual è il segreto più torbido che conosci su qualcuno e hai usato contro di loro?",
    "Se dovessi confessare la cosa più sleale che hai fatto in amore, quale sarebbe?",
    "Qual è il pensiero più perverso che hai avuto in un momento sacro o solenne?",
    "Hai mai fatto qualcosa di cui ti vergogni così tanto che cambieresti identità?",
    "Qual è la cosa più crudele che hai detto a qualcuno nei suoi ultimi momenti con te?",
    "Se potessi cancellare una persona dalla vita di qualcun altro, chi elimineresti?",
    "Qual è la fantasia più disturbante che hai mai avuto su te stesso?",
    "Hai mai provato eccitazione in una situazione di emergenza o tragedia?",
    "Qual è la cosa più vigliacca che hai fatto quando qualcuno aveva bisogno di te?",
    "Se dovessi ammettere il tuo più grande tradimento morale, quale sarebbe?",
    "Qual è la cosa più spregevole che hai fatto per evitare le conseguenze?",
    "Hai mai desiderato intensamente di poter controllare le emozioni di qualcuno?",
    "Qual è il momento in cui ti sei comportato nel modo più psicopatico?",
    "Se potessi implantare un ricordo falso in qualcuno per manipolarlo, lo faresti?",
    "Qual è la cosa più disgustosa che hai pensato durante un momento romantico?",
    "Hai mai fatto qualcosa di sessualmente inappropriato che potrebbe essere considerato predatorio?",
    "Qual è la bugia più grande che vivi quotidianamente?",
    "Se dovessi confessare la cosa più egoista che fai nelle relazioni, quale sarebbe?",
    "Qual è il pensiero più dark che hai su come finirà la tua vita?",
    "Hai mai provato piacere nel vedere qualcuno che ami soffrire per te?",
    "Qual è la cosa più immorale che hai fatto e razionalizzato completamente?",
    "Se potessi far impazzire qualcuno lentamente, chi sceglieresti?",
    "Qual è la cosa più patetica che hai fatto per evitare di essere abbandonato?",
    "Hai mai avuto fantasie violente così dettagliate da spaventarti?",
    "Qual è il momento in cui hai realizzato di essere capace di vero male?",
    "Se dovessi ammettere la cosa più manipolativa che fai inconsciamente, quale sarebbe?",
    "Qual è la cosa più disgustosa che hai fatto per curiosità morbosa?",
    "Hai mai mentito su qualcosa di così grave che potrebbe distruggere vite?",
    "Qual è il segreto più nero che porterai nella tomba?",
    "Se potessi far rivivere a qualcuno il suo peggior incubo, chi sceglieresti?",
    "Qual è la cosa più spregevole che hai pensato durante una perdita di qualcun altro?",
    "Hai mai provato eccitazione sessuale in un contesto completamente inappropriato?",
    "Qual è la fantasia più disturbante che hai su come potresti ferire qualcuno emotivamente?",
    "Se dovessi confessare la cosa più egoista che hai fatto a spese di chi ti ama, cosa sarebbe?",
    "Qual è il pensiero più crudele che hai avuto su qualcuno mentre fingevi di consolarlo?",
    "Hai mai desiderato che qualcuno soffrisse esattamente come hai sofferto tu?",
    "Qual è la cosa più immorale che hai fatto giustificandola come 'necessaria'?",
    "Se potessi cancellare la felicità dalla vita di qualcuno, lo faresti?",
    "Qual è il momento in cui ti sei odiato di più per quello che hai pensato?",
    "Hai mai fatto qualcosa di così vergognoso che negheresti anche sotto tortura?",
    "Qual è la cosa più sleale che hai fatto per ottenere l'amore di qualcuno?",
    "Se dovessi ammettere la tua più grande debolezza morale, quale sarebbe?",
    "Qual è la fantasia più oscura che hai su come potrebbe finire la vita di qualcuno?",
    "Hai mai provato piacere nel distruggere la fiducia che qualcuno aveva in te?",
    "Qual è la cosa più disgustosa che hai fatto per sentirti superiore a qualcuno?",
    "Se potessi implantare una paura irrazionale in qualcuno, quale sceglieresti?",
    "Qual è il pensiero più perverso che hai avuto su qualcuno durante il loro momento di vulnerabilità?",
    "Hai mai desiderato di poter cancellare l'esistenza di qualcuno dal mondo?",
    "Qual è la cosa più crudele che hai fatto fingendo che fosse per il loro bene?",
    "Se dovessi confessare il momento in cui ti sei sentito più mostruoso, quale sarebbe?",
    "Qual è la cosa più vile che hai pensato mentre qualcuno ti stava aiutando?",
    "Hai mai avuto fantasie così disturbanti da questionare la tua sanità mentale?",
    "Qual è la bugia più grande che vivi con te stesso ogni giorno?",
    "Se potessi rubare l'innocenza a qualcuno, come lo faresti?",
    "Qual è la cosa più spregevole che hai fatto per evitare di sembrare debole?",
    "Hai mai provato eccitazione nel controllare emotivamente qualcuno?",
    "Qual è il momento in cui hai realizzato di essere più cattivo di quanto ammetti?",
    "Se dovessi ammettere la cosa più egoista che fai nel sesso, quale sarebbe?",
    "Qual è la fantasia più disturbante che hai su come potresti manipolare qualcuno?",
    "Hai mai fatto qualcosa di così immorale che cambierebbe tutto se venisse scoperto?",
    "Qual è la cosa più crudele che hai pensato mentre fingevi di amare qualcuno?",
    "Se potessi far vivere a qualcuno il tuo peggior incubo, chi sceglieresti?",
    "Qual è il segreto più oscuro che conosci su te stesso e non ammetteresti mai?",
    "Hai mai desiderato intensamente di poter causare dolore fisico a qualcuno?",
    "Qual è la cosa più disgustosa che hai fatto per sentirti potente?",
    "Se dovessi confessare la cosa più sleale che hai fatto per vendetta, cosa sarebbe?",
    "Qual è il pensiero più malvagio che hai avuto su qualcuno che ti ama?",
    "Hai mai provato piacere nel vedere qualcuno perdere tutto?",
    "Qual è la cosa più immorale che faresti se fossi sicuro di non essere scoperto?",
    "Se potessi cancellare un momento felice dalla vita di qualcuno, quale sceglieresti?",
    "Qual è la fantasia più torbida che hai su come potresti rovinare la vita di qualcuno?",
    "Hai mai mentito su qualcosa di così grave da poter distruggere una famiglia?",
    "Qual è la cosa più patetica che hai fatto per evitare di affrontare la verità su te stesso?",
    "Se dovessi ammettere il pensiero più oscuro che hai durante i momenti intimi, quale sarebbe?",
    "Qual è la cosa più spregevole che hai fatto fingendo innocenza?",
    "Hai mai avuto fantasie di controllo così estreme da spaventarti?",
    "Qual è il momento in cui hai tradito te stesso nel modo più profondo?",
    "Se potessi impiantare un senso di colpa permanente in qualcuno, lo faresti?",
    "Qual è la cosa più crudele che hai pensato mentre qualcuno piangeva per te?",
    "Hai mai fatto qualcosa di sessualmente inappropriato che potrebbe essere considerato abuso?",
    "Qual è la bugia più elaborata che hai costruito per nascondere la tua vera natura?",
    "Se dovessi confessare la cosa più egoista che fai quando qualcuno soffre, cosa sarebbe?",
    "Qual è la fantasia più disturbante che hai su come potresti ferire psicologicamente qualcuno?",
    "Hai mai desiderato che qualcuno ti temesse più di quanto ti ami?",
    "Qual è la cosa più immorale che hai fatto per ottenere controllo su qualcuno?",
    "Se potessi cancellare la capacità di essere felice da qualcuno, lo faresti?",
    "Qual è il pensiero più malvagio che hai avuto durante un momento di perdono?",
    "Hai mai provato eccitazione nel manipolare le insicurezze di qualcuno?",
    "Qual è la cosa più disgustosa che hai fatto per sentirti amato?",
    "Se dovessi ammettere la cosa più sleale che fai nelle relazioni intime, quale sarebbe?",
    "Qual è la fantasia più oscura che hai su come potresti controllare completamente qualcuno?",
    "Hai mai fatto qualcosa di così vergognoso che cambieresti tutto di te per non averlo fatto?",
    "Qual è la cosa più crudele che hai detto a qualcuno sapendo esattamente dove colpire?",
    "Se potessi implantare un'ossessione malsana in qualcuno per te, lo faresti?",
    "Qual è il momento in cui ti sei comportato nel modo più predatorio?",
    "Hai mai avuto pensieri così disturbanti da questionare se meriti di essere amato?",
    "Qual è la cosa più spregevole che hai fatto per evitare di essere scoperto?",
    "Se dovessi confessare il tuo più grande tradimento verso te stesso, quale sarebbe?",
    "Qual è la fantasia più torbida che hai su come potresti distruggere l'autostima di qualcuno?",
    "Hai mai desiderato intensamente di poter cancellare la memoria di qualcuno per controllarli?",
          "Se dovessi trasformarti in un animale per una settimana, quale sceglieresti e perché?",
    "Quale superpotere vorresti avere durante gli esami?",
    "Hai mai provato a parlare con le piante? Credi funzioni?",
    "Qual è la cosa più inutile che hai imparato a scuola?",
    "Se la tua vita fosse un genere cinematografico, quale sarebbe?",
    "Quale odore ti trasporta immediatamente all'infanzia?",
    "Quale personaggio storico inviteresti a cena e cosa gli cucineresti?",
    "Qual è il tuo angolo preferito di casa per nasconderti?",
    "Quale oggetto comune vorresti rendere obsoleto?",
    "Quale lingua inventata vorresti saper parlare fluentemente?",
    "Qual è il tuo metodo più strano per prendere decisioni importanti?",
    "Quale emoji descrive il tuo attuale stato mentale?",
    "Quale cibo mangeresti se dovessi sopravvivere con uno solo per un mese?",
    "Quale leggenda metropolitana ti ha spaventato da bambino?",
    "Quale trend di TikTok trovi assolutamente incomprensibile?",
    "Se dovessi creare un nuovo colore, come lo chiameresti?",
    "Quale abilità da videogioco vorresti nella vita reale?",
    "Quale parola straniera usi senza motivo?",
    "Quale gadget futuristico ti delude di più per la sua assenza?",
    "Quale libro bruceresti per riscaldarti in un'emergenza?",
    "Quale momento della storia vorresti assolutamente fotografare?",
    "Quale sensazione fisica ami provare?",
    "Quale strumento musicale suoni malissimo ma con passione?",
    "Quale cartello stradale dovrebbe esistere secondo te?",
    "Quale talento inutile possiedi?",
    "Quale regola sociale infrangeresti volentieri?",
    "Quale parte del tuo corpo non ti piace nominare?",
    "Quale suono ti fa immediatamente accapponare la pelle?",
    "Quale festa inventeresti e come la celebreresti?",
    "Quale domanda faresti a un alieno appena atterrato?",
    "Quale app cancelleresti per sempre dal tuo telefono?",
    "Quale attore doppierebbe la tua vita?",
    "Quale fenomeno naturale ti lascia senza fiato?",
    "Quale mitologia vorresti fosse reale?",
    "Quale lavoro faresti se il denaro non contasse?",
    "Quale città abbandonata vorresti esplorare?",
    "Quale evento sportivo ti emoziona di più?",
    "Quale eroe dei fumetti ha la peggior identità segreta?",
    "Quale cibo mangi in modo ritualistico?",
    "Quale ricordo d'infanzia ti rende ancora felice?",
    "Quale parola cancelleresti dal dizionario?",
    "Quale luogo ti fa sentire immediatamente a casa?",
    "Quale stella del cinema sarebbe il tuo genitore adottivo?",
    "Quale suono onomatopeico faresti da supereroe?",
    "Quale leggenda familiare viene raccontata a ogni riunione?",
    "Quale videogioco descrive meglio la tua vita?",
    "Quale fiaba andrebbe riscritta?",
    "Quale animale domestico esotico vorresti?",
    "Quale regola del galateo consideri ridicola?",
    "Quale profumo vorresti diffondesse la tua casa?",
    "Quale elemento della natura rappresenta la tua personalità?",
    "Quale oggetto nel tuo zaino/borsa è totalmente inutile?",
    "Quale momento della giornata è il tuo preferito?",
    "Quale abitudine strana hai sviluppato durante i lockdown?",
    "Quale segreto custodirebbe il tuo diario segreto?",
    "Quale stile architettonico odi profondamente?",
    "Quale videoclip musicale ti ha segnato?",
    "Quale parte del corpo umano ridisegneresti?",
    "Quale colore associ al concetto di 'noia'?",
    "Quale canto di uccello trovi più irritante?",
    "Quale fenomeno di internet merita di essere studiato?",
    "Quale parola ti piace ripetere a voce alta?",
    "Quale sensazione provi quando vedi una biblioteca vuota?",
    "Quale luogo mitologico vorresti visitare?",
    "Quale strumento di tortura medievale è secondo te il più creativo?",
    "Quale personaggio dei cartoni animati ti rappresenta?",
    "Quale suono vorresti come colonna sonora della tua vita?",
    "Quale forma avrebbe la tua nuvola personale?",
    "Quale cibo mangi solo di nascosto?",
    "Quale paura infantile ti porti ancora dentro?",
    "Quale momento storico ti avrebbe fatto cambiare epoca?",
    "Quale abilità manuale possiedi che sorprende gli altri?",
    "Quale gesto quotidiano rendi più complicato del necessario?",
    "Quale posto del mondo visitare solo una volta?",
    "Quale oggetto tecnologico ti sembra magico?",
    "Quale pianta vorresti diventasse il tuo simbolo personale?",
    "Quale ricordo scolastico ti fa ancora ridere?",
    "Quale frase ripeti sempre quando sei nervoso?",
    "Quale posto in casa è il tuo rifugio segreto?",
    "Quale gioco da tavolo riflette la tua strategia di vita?",
    "Quale stagione ti ispira più malinconia?",
    "Quale animale marino ti affascina di più?",
    "Quale costume di Carnevale indosseresti ogni giorno?",
    "Quale parola ti fa immediatamente sorridere?",
    "Quale evento sportivo ti annoia profondamente?",
    "Quale caratteristica fisica innaturale vorresti avere?",
    "Quale canto popolare conosci a memoria?",
    "Quale sensazione provi quando vedi un arcobaleno?",
    "Quale elemento del meteo detesti?",
    "Quale suono vorresti eliminare per sempre?",
    "Quale erba aromatica odi profondamente?",
    "Quale luogo abbandonato vorresti riportare in vita?",
    "Quale strumento scientifico ti affascina?",
    "Quale tradizione familiare ti sembra più strana?",
    "Quale forma geometrica rappresenta il tuo carattere?",
    "Quale momento della storia dell'arte ti emoziona?",
    "Quale veicolo inventeresti per muoverti?",
    "Quale stella del cielo notturno ti ispira?",
    "Quale organo del corpo umano trovi più misterioso?",
    "Quale segno zodiacale ti descrive realmente?",
    "Quale parola d'ordine avrebbe la tua setta segreta?",
    "Quale colore vestiresti ogni giorno?",
    "Quale periodo storico vorresti fotografare?",
    "Quale gesto di cortesia consideri sopravvalutato?",
    "Quale oggetto comune attribuisci poteri magici?",
    "Quale animale domestico comunicherebbe meglio con te?",
    "Quale evento naturale ti terrorizza?",
    "Quale parte del tuo corpo ascolteresti se potesse parlare?",
    "Quale luogo ti fa sentire fuori dal mondo?",
    "Quale invenzione moderna consideri inutile?",
    "Quale figura mitologica vorresti come guida?",
    "Quale sensazione provi quando vedi un libro con le pagine tagliate?",
    "Quale materiale tessile detesti indossare?",
    "Quale momento della tua vita vorresti rivedere in VR?",
    "Quale suono della natura ti calma?",
    "Quale abilità circense possiederesti?",
    "Quale film d'animazione ha cambiato la tua infanzia?",
    "Quale odore associ all'estate?",
    "Quale segreto custodisce il tuo cassetto più disordinato?",
    "Quale forma d'arte ti lascia perplesso?",
    "Quale gesto quotidiano rendi poetico?",
    "Quale oggetto nel tuo frigorifero stupirebbe un ospite?",
    "Quale luogo ti ispira per scrivere?",
    "Quale attività manuale ti rilassa?",
    "Quale parola dialettale usi con orgoglio?",
    "Quale elemento naturale vorresti controllare?",
    "Quale sensazione provi quando vedi una lavagna vuota?",
    "Quale monumento mondiale abbatteresti?",
    "Quale abitudine notturna hai?",
    "Quale mito scientifico credevi da bambino?",
    "Quale tessuto ti fa rabbrividire al tatto?",
    "Quale momento della giornata è il tuo nemico?",
    "Quale gioco da bambini vorresti reintrodurre?",
    "Quale tipo di nuvola ti affascina?",
    "Quale parola tecnologica abusi?",
    "Quale evento storico ti ha insegnato qualcosa?",
    "Quale creatura mitologica ti protegge?",
    "Quale stile di danza proveresti?",
    "Quale fenomeno ottico ti lascia a bocca aperta?",
    "Quale luogo letterario vorresti visitare?",
    "Quale colore ti rappresenta in un giorno noioso?",
    "Quale regalo hai riciclato?",
    "Quale suono meccanico ti piace?",
    "Quale attività ti fa perdere la nozione del tempo?",
    "Quale segreto di famiglia sospetti?",
    "Quale personaggio televisivo ti rappresenta?",
    "Quale cibo ti ricorda un momento imbarazzante?",
    "Quale luogo ti fa sentire un personaggio cinematografico?",
    "Quale strumento musicale suoneresti in una banda improvvisata?",
    "Quale sensazione provi quando vedi un orologio rotto?",
    "Quale stagione ti trasforma?",
    "Quale evento astronomico non vorresti perdere?",
    "Quale odore detesti profondamente?",
    "Quale parte del corpo umano trovi più affascinante?",
    "Quale luogo abbandonato esploreresti?",
    "Quale oggetto antico possiedi?",
    "Quale parola straniera usi senza motivo?",
    "Quale gesto ripeti quando sei concentrato?",
    "Quale fenomeno atmosferico ti ipnotizza?",
    "Quale ricetta cucineresti per sopravvivere?",
    "Quale momento storico ti avrebbe fatto cambiare idea?",
    "Quale abilità animale vorresti?",
    "Quale colore ti rappresenta quando sei arrabbiato?",
    "Quale suono naturale ti sveglia volentieri?",
    "Quale personaggio delle fiabe ti somiglia?",
    "Quale luogo ti fa sentire un esploratore?",
    "Quale evento sportivo ti emoziona?",
    "Quale tecnologia ti sembra magica?",
    "Quale sensazione provi quando vedi un tramonto?",
    "Quale parte del tuo corpo ascolteresti se potesse parlare?",
    "Quale elemento naturale domineresti?",
    "Quale ricordo ti fa ridere da solo?",
    "Quale oggetto quotidiano attribuisci un'anima?",
    "Quale momento del passato rivivresti?",
    "Quale parola ti descrive in una parola?",
    "Quale stagione musicale preferisci?",
    "Quale fenomeno scientifico ti lascia perplesso?",
    "Quale luogo ti ispira tranquillità?",
    "Quale cibo mangi in modo bizzarro?",
    "Quale evento storico vorresti aver fotografato?",
    "Quale personaggio storico vorresti intervistare?",
    "Quale abitudine mattutina hai?",
    "Quale suono ti fa addormentare?",
    "Quale colore associ alla felicità?",
    "Quale momento della tua vita vorresti condividere?",
    "Quale elemento della natura ti rappresenta?",
    "Quale luogo ti fa sentire creativo?",
    "Quale oggetto nel tuo armadio non indossi mai?",
    "Quale parola ti piace pronunciare?",
    "Quale fenomeno naturale ti spaventa?",
    "Quale ricordo d'infanzia ti emoziona?",
    "Quale personaggio immaginario vorresti conoscere?",
    "Quale attività ti fa sentire vivo?",
    "Quale odore ti riporta a un momento felice?",
    "Quale luogo ti fa sentire ispirato?",
    "Quale momento del giorno preferisci?",
    "Quale sensazione provi quando vedi il mare?",
    "Quale oggetto porti sempre con te?",
    "Quale parola ti rappresenta?",
    "Quale stagione ti piace di più?",
    "Quale suono ti rilassa?",
    "Quale colore ti calma?"
  ];

  try {
    const truthMessage = truths[Math.floor(Math.random() * truths.length)];
    const thumbPath = path.join('./src/img/menu', 'bonk.png');
    
    const thumbBuffer = fs.existsSync(thumbPath) 
      ? fs.readFileSync(thumbPath) 
      : null;

    await conn.sendMessage(m.chat, {
      text: `🔮 *T R U T H* 🔮\n\n${truthMessage}\n\n_Rispondi con sincerità!_`,
      contextInfo: {
        externalAdReply: {
          title: "💎 Phishy Truth Challenge",
          body: "Osate rispondere con la verità?",
          thumbnail: thumbBuffer,
          sourceUrl: "",
          mediaType: 1,
          renderLargerThumbnail: false
        }
      }
    }, { quoted: m });

  } catch (error) {
    console.error('[TRUTH ERROR]', error);
    reply('❌ Si è verificato un errore nel generare la domanda Truth.');
  }
};

handler.command = /^(truth|verità|domandascottante|verita)$/i;
handler.tags = ['game'];
handler.help = ['truth', 'verità', 'domandascottante'];
handler.group = true;
handler.register = true;

export default handler;