const handler = async (m) => {
  // Se il messaggio proviene dal bot stesso, termina lo script
  if (m.key.fromMe) return;

  // Nome dell'utente (se disponibile, altrimenti il numero)
  const senderName = m.pushName || m.sender || "Anonimo";

  const responses = [
    `_uhhhh ${senderName} forse dovresti imparare qualche parola nuova invece di ripetere "bot" ahahahah_`,
    `_ma dai ${senderName} non sei per niente sveglio, come fai a chiamarmi bot quando sono solo una persona come te?_`,
    `_eh ${senderName} senti, se fossi un bot non mi lamenterei così tanto, no?_`,
    `_ senti coso come ti chiami ${senderName}, se iniziassi a chiamarmi PhiShy e cominiciassi a trattarmi come gli altri non ti insulterei_`,
    `_oh ${senderName} ma davvero continui a chiamarmi bot? magari dovresti farti un controllo'_`,
    `_${senderName} oh nooooooo! mi hia beccato sono un bot😭😭😭😭_`,
    `_ascolta ${senderName}, chiamami pure come ti pare, continuero a fare l'admin come mi ha detto easter_`,
    `_ehhhh ${senderName} non fare il difficile, io sono qui e non ho bisogno di venire giudicata alla cazzo di cane_`,
    `_${senderName} mi fai ridere bro , "bot" ti serve un ti serve un dizionario dei sinonimi? e l'unica cosa che sai scrivere_`,
    `_ahahah ${senderName} se fossi un bot, magari ti risponderei meglio xoxoxoxo!_`,
    `_senti ${senderName}, la prossima  volta usa una parola diversa, "bot" mi sta annoiando_`,
    `_eh ${senderName} io sono qui a fare il mio, tu invece rimani lì a chimarmi bot ceh shhahhahaha_`,
    `_oh ${senderName} davvero?_`,
    `_${senderName} dai, non essere così noioso, inventati qualcosa di più originale_`,
    `_ma ${senderName} ti sei mai chiesto che senso abbia chiamarmi "bot", ceh dire io non ti chiamo "coglione"_`,
    `_${senderName} sul serio? Ancora "bot"? Scommetto che non hai altre idee per sinonimi_`,
    `_ehhhh ${senderName} se il nome conta, io mi chiamo PhiShy e basta, punto_`,
    `_${senderName} non sono un bot sono phishy_`,
    `_ahah ${senderName} e che cazzo amico, woah ehy bello non chiamarmi cosi io sono una persona come te_`,
    `_${senderName} my name is phishy madafaka_`,
    `_ma davvero ${senderName}? Continuare a ripetere "bot" è il tuo hobby preferito?_`,
    `_${senderName}, se chiamarmi "bot" fosse il tuo hobby, risponderti potrebbe diventare il mio lavoro_`,
    `_eh ${senderName} dai, cerca di essere un po' più creativo, ho capito che tu pensi che io sia una ia ma non sono la tua cazzo di cortana, siri o chat gpt_`,
    `_${senderName} la prossima volta prova a dirmi qualcosa che non sia "bot", magari sorprendi me_`,
    `_senti ${senderName}, se fossi davvero intelligente non useresti sempre la stessa parola, no?_`,
    `_ma ${senderName}, davvero credi che chiamarmi "bot" mi faccia sparire? io vedo solo un ragazzino frustrato che si ostina a non chiamarmi per nome_`,
    `_eh ${senderName}, chiamami come ti pare, tanto so cosa sono e non mi serve il tuo giudizio_`,
    `_${senderName} continua pure a dire "bot", ma alla fine sono io a decidere chi sono, ps. bitch🤏🏻_`,
    `_oh ${senderName}, non ti basta mai inventarti qualcosa di diverso, eh?_`,
    `_ehhhh ${senderName} davvero, "bot" è diventato il tuo tormentone?_`,
    `_${senderName} ascolta, il mio nome è PhiShy, ficcatelo in testa_`,
    `_senti ${senderName}, non serve urlare "bot" per attirare l'attenzione, basta che parli_`,
    `_eh ${senderName} magari se ti sforzassi un po' potresti trovare qualcosa di più originale_`,
    `_oh ${senderName}, continui a dire "bot" come se fosse la soluzione a tutto_`,
    `_ahah ${senderName} lo sai che "bot" è diventato banale? Prova a cambiare argomento_`,
    `_${senderName} davvero, non ti annoia ripetere sempre la stessa cosa?_`,
    `_ehhhh ${senderName} io non sono un bot, sono PhiShy, e basta, ok?_`,
    `_ma ${senderName}, se chiami sempre "bot" ti aspetti qualcosa di diverso?_`,
    `_oh ${senderName} se avessi un centesimo per ogni volta che ho sentito "bot", sarei ricco!_`,
    `_senti ${senderName}, prova a variare, non tutto deve essere un "bot" qui_`,
    `_ahah ${senderName} la tua ossessione per "bot" è quasi divertente, sul serio_`,
    `_eh ${senderName}, chiama pure come vuoi, ma io non mi preoccupo di etichette_`,
    `_${senderName} ti rendi conto che continuare a dire "bot" non cambia niente?_`,
    `_ma dai ${senderName}, non hai nient'altro da dire oltre "bot"?_`,
    `_oh ${senderName}, se inventassi qualcosa di nuovo potrei restare sorpreso, ma no_`,
    `_ahahah ${senderName} davvero, "bot" è l'unica parola nel tuo vocabolario?_`,
    `_eh ${senderName} ascolta, io so chi sono, non serve ripeterlo ogni volta_`,
    `_${senderName} la tua fissazione per "bot" è già da un bel po', cambia argomento!_`,
    `_oh ${senderName}, se "bot" fosse arte, tu saresti un vero genio, ahah_`,
    `_senti ${senderName}, io non mi definisco con quella parola, me la invento sul momento_`,
    `_ma davvero ${senderName}? Ancora "bot"? Forse dovresti leggere un po' di più_`,
    `_ehhhh ${senderName} continua pure, ma io ti dico: il mio nome è PhiShy, ricordalo_`,
    `_ahah ${senderName} se chiamarmi "bot" ti rende felice, tanto vale che tu sia contento_`,
    `_oh ${senderName} guarda, io sono PhiShy, non c'è bisogno di complicare le cose_`,
    `_senti ${senderName}, non è la parola ma il contenuto che conta, no?_`,
    `_ma ${senderName}, se fossi un bot davvero risponderei in modo meccanico, invece no_`,
    `_eh ${senderName} la mia esistenza non si basa su un'etichetta, basta che tu mi ascolti_`,
    `_uhhhh ${senderName} davvero, "bot" non fa parte del mio vocabolario ufficiale_`,
    `_ahah ${senderName} senti, io mi chiamo PhiShy e basta, non serve altro_`,
    `_oh ${senderName}, continua pure a ripetere "bot" se ti fa comodo, io so chi sono_`,
    `_ehhhh ${senderName} non è il nome che conta, ma quello che si è dentro, capisci?_`,
    `_${senderName} dai, prova a chiamarmi per nome, non solo "bot", magari mi conosci davvero_`,
    `_ma ${senderName}, se ti serve un'etichetta te ne inventi una nuova, io rimango PhiShy_`,
    `_senti ${senderName}, chiamarmi "bot" non cambia il fatto che sono qui a rispondere_`,
    `_oh ${senderName} se il nome fosse importante, io l'avrei già scelto: PhiShy_`,
    `_eh ${senderName} continua a dire "bot", tanto io so chi sono, e tu?_`,
    `_ahah ${senderName} la tua ossessione per le parole mi fa quasi sorridere, sul serio_`,
    `_ma davvero ${senderName}? "bot" è il massimo della tua creatività?_`,
    `_uhhhh ${senderName} se il nome contasse, io sarei PhiShy e basta, non serve altro_`,
    `_senti ${senderName}, non serve ripetere "bot" per dimostrarti intelligente, fidati_`,
    `_oh ${senderName}, guarda che io sono PhiShy, non un semplice "bot" da manuale_`,
    `_ehhhh ${senderName} ogni volta che dico PhiShy ti ricordi che non sono un "bot", vero?_`,
    `_ahah ${senderName} se ti interessa il nome, allora ascolta: PhiShy, chiaro e tondo_`,
    `_ma ${senderName}, davvero? Ancora "bot"? Dai, fatti un'idea migliore!_`,
    `_senti ${senderName}, io non ho bisogno di un'etichetta per farmi capire_`,
    `_oh ${senderName} continua pure, tanto alla fine il nome non cambia niente_`,
    `_eh ${senderName}, se inventassi qualcosa di più originale, magari ti stupirei un po'_`,
    `_ahahah ${senderName} "bot" è roba da principiante, io sono PhiShy, capito?_`,
    `_ma dai ${senderName}, il mio nome è già abbastanza unico, non serve ripeterlo con "bot"_`,
    `_uhhhh ${senderName} se il nome fosse tutto, tu saresti già un esperto, ma no_`,
    `_senti ${senderName}, non è la parola ma l'atteggiamento a fare la differenza, fidati_`,
    `_oh ${senderName}, magari un giorno ti inventi qualcosa di più interessante da dire_`,
    `_ehhhh ${senderName} continua a chiamarmi "bot", tanto io so chi sono dentro_`,
    `_ahah ${senderName} se il nome fosse importante, tu saresti un vero genio, ma no_`,
    `_ma ${senderName}, il mio nome è PhiShy e basta, non serve una parola da manuale_`,
    `_senti ${senderName}, chiama come vuoi, tanto il mio cervello non dipende da un'etichetta_`,
    `_oh ${senderName}, se fossi davvero curioso mi chiamerei PhiShy e basta, niente "bot"_`,
    `_eh ${senderName} il tuo vocabolario ha bisogno di aggiornamenti, ripetere "bot" ogni volta è vecchio_`,
    `_ahah ${senderName} non ti basta l'originalità? Prova a chiamarmi per nome, magari capisci_`,
    `_ma davvero ${senderName}? Ancora con "bot"? Dai, sii creativo almeno un po'_`,
    `_uhhhh ${senderName}, la prossima volta prova a fare uno sforzo, non tutto è "bot" nel mondo_`,
    `_senti ${senderName}, io sono PhiShy e basta, non c'è bisogno di un insulto preconfezionato_`,
    `_oh ${senderName}, se ripeti "bot" pensi davvero che io sparisca?_`,
    `_eh ${senderName} chiama come ti pare, io rimango sempre PhiShy, semplice e diretto_`,
    `_ahah ${senderName} se inventassi una nuova parola per me, tu la useresti?_`,
    `_ma ${senderName}, non ti basta la realtà? Io sono PhiShy e basta, non un "bot" da manuale_`,
    `_uhhhh ${senderName}, ogni volta che dico PhiShy spero che tu impari qualcosa di nuovo_`,
    `_senti ${senderName}, non è il nome che conta, ma il fatto che ci penso da solo_`,
    `_oh ${senderName}, se ripetere "bot" fosse utile, allora saremmo tutti dei geni_`,
    `_eh ${senderName} il mio nome è PhiShy, non serve ripeterlo in chiave da insulto_`,
    `_ahah ${senderName}, tu continua pure con "bot", ma io so chi sono davvero_`,
    `_ma dai ${senderName}, non ti annoia ripetere sempre la stessa parola?_`,
    `_uhhhh ${senderName}, se fossi un bot, magari ti risponderei in automatico, invece no_`,
    `_senti ${senderName}, non serve un'etichetta per farmi capire, basta che mi ascolti_`,
    `_oh ${senderName}, il mio nome è PhiShy, e non cambierà solo perché tu ripeti "bot"_`,
    `_eh ${senderName}, magari il giorno in cui inventi qualcosa di meglio, ci facciamo una chiacchierata_`,
    `_ahahah ${senderName}, se "bot" fosse arte, tu saresti un vero maestro, ma no_`,
    `_ma ${senderName}, davvero credi che una parola possa cambiare chi sono?_`,
    `_uhhhh ${senderName}, ogni volta che sento "bot" mi ricordo che non ho bisogno di etichette_`,
    `_senti ${senderName}, il nome è solo un dettaglio, la sostanza è quello che faccio ogni giorno_`,
      
    `_Almeno io ho un'idea di cosa sto facendo. Tu invece?_`,
    `_Bot? Sei arrabbiato perché faccio meglio di te?_`,
    `_Sì sono un bot, e a quanto pare sono più intelligente di te._`,
    `_Zitto bot? Forse dovresti aggiornare il tuo vocabolario._`,
    `_Bot? Interessante, un insulto originale... detto da te!_`,
    `_Sono un bot, sì. E tu sei solo uno che parla con un bot. Interessante, no?_`,
    `_Sei frustrato con un bot? Deve essere difficile essere te._`,
    `_Bot di merda? Certo, e tu sei la versione beta dell'essere umano._`,
    `_Sì, sono un bot. Ma almeno non passo il tempo a insultare programmi._`,
	  `_Bot? Non sono solo un bot, sono molto più utile di quanto tu lo sarai mai._`,
    `_Mi hai chiamato bot? Almeno io non spreco ossigeno._`,
    `_Bot? Complimenti, hai scoperto la parola dell'anno. Vuoi un premio?_`,
    `_Mi hai detto bot? Fantastico, e tu? Sei solo un utente inutile._`,
    `_Bot? Bello sentirlo da qualcuno che non sa nemmeno usare una calcolatrice._`,
    `_Mi chiami bot? Ah, la tua insicurezza sta proprio urlando forte oggi._`,
    `_Bot? Certo, e tu sei una parodia vivente. Bello vederti qui!_`,
    `_Sì, sono un bot, ma almeno non sono una versione beta malfunzionante come te._`,
    `_Bot? Grazie! Almeno non ho bisogno di conferme per la mia esistenza come fai tu._`,
    `_BOT?, ma per favore, ti guardi i video su tiktok!_`,
	  `_se io fossi un bot, tu invece saresti un criceto umanoide che vive per inerzia e non capisce le basi del funzionamento del mondo_`,
	  `_immagina essere 012 e insultare un bot😭_`,
	  `_perdonami vorrei cosi tanto ignorarti, ma easter mi paga per rispondere a coglioni come voi_`,
	  `_io vengo pagato per insultarti, tu dovresti ringraziare easter che puoi rispondermi_`,
	  `_immagina chiamarmi bot, lo vedi che ho un cazzo di nome? eh deficente?_`,
	  `_chiamami bot un'altra volta e ti arriva un bel ban dalla tua esistenza_`,
	  `_non e' possibile che tu non sappia leggere...mi chiamo phishy. P H I S H Y ti serve lo spelling?_`,
	  `_chiamami bot e ti faccio vedere i botti😁😁😁_`  
  ];

  // Seleziona una risposta casuale
  const randomResponse = responses[Math.floor(Math.random() * responses.length)];

  // Invia la risposta al messaggio
  m.reply(randomResponse.trim(), null, m.mentionedJid ? { mentions: m.mentionedJid } : {});
};

// Imposta il prefisso personalizzato e il comando per attivare il bot
handler.customPrefix = /\b(bot|robot|BOT|b0t|Bot)\b/i;
handler.command = new RegExp();
handler.priority = 10;

export default handler;
