const handler = async (m, {
  conn, groupMetadata,
}) => {
  if (!m.isGroup) {
    throw '';
  }
  const gruppi = global.db.data.chats[m.chat];
  if (gruppi.spacobot === false) {
    throw '';
  }
  const toM = (a) => '@' + a.split('@')[0];
  const ps = groupMetadata.participants.map((v) => v.id);
  const a = ps.getRandom();
  m.reply(`${toM(a)} ${pickRandom([
    'ha fatto bestemmiare un prete lanciandoli un petardo addosso',
    'mi usa solo per masturbarsi sulle foto zozze che invio',
    'è innamorato/a di un membro del gruppo',
    'non si fa il bidet',
    'adora vestirsi del sesso opposto, fotografarsi per poi masturbarsi',
    'adora le donne grasse',
    'ha i piedi puzzolenti',
    'dopo che fa la cacca guarda con orgoglio il suo capolavoro e poi tira lo sciaqquone',
    'masturba il suo cane',
    'ha iniziato a mangiare il calippo per imparare a fare i bocchini',
    'ha preso più cazzi che forchette in bocca',
    'ha una collezione di 1 TB di porno trans',
    'si fa leccare il suo organo genitale dal suo cane',
    'spende 1000€ al mese in escorts e mente al suo compagno sullo stipendio',
    'sa che uno del gruppo è gay',
    'è più ignorante di miss Italia per quello non parla tanto',
    'è vergine',
    'vuole più bene alla sua cagna che alla cagna della sorella',
    'usa Internet Explorer',
    'fa finta di lasciar vincere il cugino di 12 anni alla PlayStation ma la realtà è una sega mortale',
    'la scorsa notte si è pisciato/a addosso',
    'ha il culo sporco di merda',
    'scoreggia in discoteca, tanto non lo sente nessuno',
    'lo eccita la fantasia di farsi trombare da un cane',
    'non si lava i denti il fine settimana',
    'a 10 anni andò a un funerale e invece di dire condoglianze disse tanti auguri alla vedova',
    // Nuove frasi più piccanti, stronze e bastarde:
    'ha mandato nude alla mamma per sbaglio',
    'ha la personalità di una patata bollita',
    'ha la stessa utilità di un ombrello bucato',
    'ha la simpatia di un cactus in un bidet',
    'ha la profondità emotiva di una pozzanghera',
    'ha la velocità di risposta di un fax nel 2025',
    'ha la memoria di un pesce rosso sotto acido',
    'ha la stessa energia di una domenica sera prima di lunedì',
    'ha la stessa credibilità di un influencer su Temptation Island',
    'ha la stessa fortuna di uno che trova solo monete da 1 cent',
    'ha la stessa eleganza di un cinghiale in tangenziale',
    'ha la stessa logica di un regolamento di condominio',
    'ha la stessa pazienza di un bambino davanti a un regalo',
    'ha la stessa coerenza di un politico in campagna elettorale',
    'ha la stessa autostima di una zanzara in inverno',
    'ha la stessa utilità di un tutorial su come respirare',
    'ha la stessa intelligenza di una sedia rotta',
    'ha la stessa presenza scenica di un comodino',
    'ha la stessa voglia di vivere di un lunedì mattina',
    'ha la stessa originalità di una password "123456"',
    'ha la stessa delicatezza di un elefante in cristalleria',
    'ha la stessa fantasia di un modulo INPS',
    'ha la stessa ironia di un avviso di Equitalia',
    'ha la stessa empatia di un tornello della metro',
    'ha la stessa finezza di un rutto a tavola',
    'ha la stessa onestà di un parcheggiatore abusivo',
    'ha la stessa puntualità di Trenitalia',
    'ha la stessa trasparenza di una porta blindata',
    'ha la stessa allegria di un funerale sotto la pioggia',
    'ha la stessa lucidità di uno dopo 10 shot di tequila',
    'ha la stessa fortuna di chi trova solo parcheggi a pagamento',
    'ha la stessa simpatia di una multa sul parabrezza',
    'ha la stessa logica di un oroscopo su Facebook',
    'ha la stessa utilità di un toast senza pane',
    'ha la stessa profondità di una pozzanghera in agosto',
    'ha la stessa energia di una batteria scarica',
    'ha la stessa coerenza di un orologio rotto',
    'ha la stessa pazienza di un modem 56k',
    'ha la stessa eleganza di un pigiama a pois',
    'ha la stessa autostima di una calcolatrice senza pile',
    'ha la stessa originalità di una fotocopia',
    'ha la stessa ironia di un modulo delle tasse',
    'ha la stessa empatia di un call center automatico',
    'ha la stessa finezza di un camionista in autogrill',
    'ha la stessa onestà di un televenditore notturno',
    'ha la stessa puntualità di un autobus a Napoli',
    'ha la stessa trasparenza di una tenda nera',
    'ha la stessa allegria di un lunedì di pioggia',
    'ha la stessa lucidità di uno dopo la sagra del vino',
    'ha fatto sesso con una cugina e lo rifarebbe',
    'ha leccato il water per una scommessa persa',
    'ha pagato followers finti e si vanta pure',
    'ha fatto coming out solo per non pagare la cena',
    'ha usato la carta di credito della nonna per OnlyFans',
    'ha fatto sesso in bagno durante una festa di famiglia',
    'ha le mutande bucate da 3 giorni',
    'ha fatto pipì nella bottiglia e poi l’ha bevuta per sbaglio',
    'ha mandato un vocale di bestemmie al gruppo della parrocchia',
    'ha fatto finta di essere malato per non uscire con voi',
    'ha scritto "ti amo" a due persone diverse lo stesso giorno',
    'ha fatto sesso con una persona che non ricorda nemmeno il nome',
    'ha rubato soldi dalla borsa della mamma',
    'ha fatto la cacca in mare e ha dato la colpa ai pesci',
    'ha usato la lingua dove non batte il sole',
    'ha fatto sesso in macchina davanti a un asilo',
    'ha mandato foto hot a un professore per sbaglio',
    'ha fatto sesso con una persona solo per una scommessa',
    'ha fatto finta di amare qualcuno solo per i regali',
    'ha fatto sesso in un cimitero',
    'ha fatto la doccia con la nonna',
    'ha fatto sesso con una persona sposata',
    'ha fatto sesso in un bagno pubblico e si è vantato/a',
    'ha fatto sesso con un ex solo per vendetta',
    'ha fatto sesso in spiaggia e si è scottato/a il sedere',
    'ha fatto sesso con una persona del gruppo',
    'ha fatto sesso con una persona appena conosciuta',
    'ha fatto sesso con una persona che non gli piaceva',
    'ha fatto sesso con una persona solo per soldi',
    'ha fatto sesso con una persona solo per noia',
    'ha fatto sesso con una persona solo per curiosità',
    'ha fatto sesso con una persona solo per scommessa',
    'ha fatto sesso con una persona solo per dispetto',
    'ha fatto sesso con una persona solo per gelosia',
    'ha fatto sesso con una persona solo per vendetta',
    'ha fatto sesso con una persona solo per pietà',
    'ha fatto sesso con una persona solo per interesse',
    'ha fatto sesso con una persona solo per convenienza',
    'ha fatto sesso con una persona solo per capriccio',
    'ha fatto sesso con una persona solo per sfida',
    'ha fatto sesso con una persona solo per gioco',
    'ha fatto sesso con una persona solo per passare il tempo',
    'ha fatto sesso con una persona solo per sentirsi vivo/a',
    'ha fatto sesso con una persona solo per sentirsi desiderato/a',
    'ha fatto sesso con una persona solo per sentirsi importante',
    'ha fatto sesso con una persona solo per sentirsi amato/a',
    'ha fatto sesso con una persona solo per sentirsi speciale',
    'ha fatto sesso con una persona solo per sentirsi diverso/a',
    'ha fatto sesso con una persona solo per sentirsi normale',
    'ha fatto sesso con una persona solo per sentirsi accettato/a',
    'ha fatto sesso con una persona solo per sentirsi parte del gruppo',
    'ha fatto sesso con una persona solo per sentirsi meno solo/a',
    'ha fatto sesso con una persona solo per sentirsi meno triste',
    'ha fatto sesso con una persona solo per sentirsi meno annoiato/a',
    'ha fatto sesso con una persona solo per sentirsi meno stressato/a',
    'ha fatto sesso con una persona solo per sentirsi meno arrabbiato/a',
    'ha fatto sesso con una persona solo per sentirsi meno frustrato/a',
    'ha fatto sesso con una persona solo per sentirsi meno in colpa',
    'ha fatto sesso con una persona solo per sentirsi meno insicuro/a',
    'ha fatto sesso con una persona solo per sentirsi meno inadeguato/a',
    'ha fatto sesso con una persona solo per sentirsi meno sbagliato/a',
    'ha fatto sesso con una persona solo per sentirsi meno giudicato/a',
    'ha fatto sesso con una persona solo per sentirsi meno escluso/a',
    'ha fatto sesso con una persona solo per sentirsi meno emarginato/a',
    'ha fatto sesso con una persona solo per sentirsi meno diverso/a',
    'ha fatto sesso con una persona solo per sentirsi meno normale',
    'ha fatto sesso con una persona solo per sentirsi meno speciale',
    'ha fatto sesso con una persona solo per sentirsi meno importante',
    'ha fatto sesso con una persona solo per sentirsi meno desiderato/a',
    'ha fatto sesso con una persona solo per sentirsi meno vivo/a',
  ])}`, null, {
    mentions: [a],
  });
};
handler.customPrefix = /segreto/i;
handler.command = new RegExp;
handler.priority = 10;
export default handler;
function pickRandom(list) {
  return list[Math.floor(Math.random() * list.length)];
}