// Motivi di addio generici
export const motiviAddio = [
  "_ha deciso di unirsi a un monastero digitale dove non si può usare WhatsApp 🧘_",
    "_è stato assunto come tester professionista di divani (deve stare sdraiato 8 ore al giorno) 🛋️_",
    "_ha vinto un concorso per diventare l'ambasciatore mondiale della noia 🏆_",
    "_sta seguendo il suo sogno di diventare un cercatore di funghi magici 🍄_",
    "_ha scoperto che la vita esiste fuori da WhatsApp ed è andato a verificare 🌍_",
    "_è stato reclutato dalla CIA per una missione segreta di monitoraggio dei gruppi WhatsApp 🕵️_",
    "_ha deciso di dedicarsi alla coltivazione di cactus emotivi 🌵_",
    "_è diventato un influencer di silenzi imbarazzanti 🤫_",
    // ...continua con tutte le altre frasi...
    "ha deciso di vivere come un pomodoro e ora trascorre le giornate al sole 🍅"
];


// Gruppi con addio specifico
export const gruppiAddio = [
  {
    jid: '120363401630273537@g.us', // Viridi Celesti
frasi: [
  "Ha lasciato Viridi Celesti perché non si sentiva a suo agio tra le anime pure! 💚",
  "Un unicorno gli ha consigliato di cercare la felicità altrove. 🌟",
  "Ha deciso di partire per un viaggio spirituale tra i gruppi WhatsApp. 🌍",
  "Ha abbandonato Viridi Celesti per diventare monaco del silenzio digitale. 🧘",
  "Ha lasciato il gruppo per dedicarsi alla coltivazione di cactus emotivi. 🌵",
  "Ha deciso di unirsi a un monastero digitale dove non si può usare WhatsApp 🧘",
  "È stato assunto come tester professionista di divani (deve stare sdraiato 8 ore al giorno) 🛋️",
  "Ha vinto un concorso per diventare l'ambasciatore mondiale della noia 🏆",
  "Sta seguendo il suo sogno di diventare un cercatore di funghi magici 🍄",
  "Ha scoperto che la vita esiste fuori da WhatsApp ed è andato a verificare 🌍",
  "È stato reclutato dalla CIA per una missione segreta di monitoraggio dei gruppi WhatsApp 🕵️",
  "È diventato un influencer di silenzi imbarazzanti 🤫",
  "Non si era accorto che su viridi non ci possono stare i pedofili e ha deciso di andarsene 🚫",
  "se ne è andato prima che gli dicessimo che qui non si può fare spam di link di altri gruppi WhatsApp 🚫",
  "È stato assunto come tester professionista di sacchi da box (era lui il sacco) 🥊",
  "non sopportava di ricevere 10000 notifica da viridi",
  "era troppo permarosa",
  "non sapeva stare al suo posto",
  "non sopportava di essere il primo a pagare la pizza virtuale 🍕",
  "se ne è andato prima di ricevere il terzo warn",
  "si è preso una vacanza",
  "viridi celesti è gay 🏳️‍🌈",
  "non capiva la differenza fra un gruppo e una community, la confusione lo ha fatto abbandonare la bacheca 📜",
  "non sopportava di essere l'unico a non avere un veicolo per le gare 🚗",
  "non riusciva a stare al passo con le regole del gruppo e ha deciso di andarsene 🚫",
  "non riusciva a gestire il suo QI negativo e ha deciso di cercare un gruppo più positivo 🧠",
  "non sopportava le battute sui cactus emotivi e ha deciso di andarsene 🌵",
  "ha scoperto che il miami bailey butcher si trovava su viridi e ha deciso di andarsene 🥩",
  "ha visto troppo rick e morty e ha capito che viridi celesti non era una avventura per lui 🚀",
  "sapete una cosa? non lo so, ma ha deciso di andarsene comunque 🤷",
  "dopo aver sculettato per ore ha capito la sua strada🚶",
  "skyler white gli ha detto che non era il suo posto e ha deciso di andarsene 🏠",
  "ha il cancr0 e ha deciso di prendersi una pausa per curarsi 🎗️",
  "non puo trovare più il suo telefono 📱",
  "È diventato allergico al colore verde e ha dovuto abbandonare tutto ciò che è Viridi 🟢",
  "Ha scoperto di essere daltonico e non riusciva più a distinguere i Viridi dai Celesti 👁️",
  "Si è convertito al minimalismo digitale e può stare solo in gruppi con massimo 3 membri 📵",
  "È stato rapito dagli alieni e ora comunica solo tramite segnali di fumo 👽",
  "Ha iniziato una carriera come mimo e ha fatto voto di silenzio perpetuo 🎭",
  "Si è iscritto a un corso di velocità della luce e ora va troppo veloce per WhatsApp ⚡",
  "È diventato un collezionista di bolle di sapone e deve dedicarci tutto il suo tempo 🫧",
  "Ha scoperto di essere intollerante ai messaggi vocali e qui ce n'erano troppi 🎙️",
  "È partito per cercare l'Atlantide e là non c'è copertura 🌊",
  "Ha deciso di diventare un eremita digitale e vive solo di like su Instagram 🏔️",
  "È stato assunto come assaggiatore di aria fresca in montagna 🏔️",
  "Ha iniziato una relazione seria con la sua PlayStation e non ha più tempo 🎮",
  "È diventato troppo ricco e ora può permettersi solo gruppi premium a pagamento 💰",
  "Ha scoperto di essere allergico alle emoji e qui ce ne sono troppe 😷",
  "È partito per un reality show su un'isola deserta senza WiFi 🏝️",
  "Ha deciso di seguire una dieta digitale e WhatsApp ha troppe calorie 📱",
  "È stato adottato da una famiglia di pinguini in Antartide 🐧",
  "Ha iniziato a parlare solo in haiku e qui nessuno lo capiva 🎋",
  "È diventato un detective privato specializzato in messaggi eliminati 🔍",
  "Ha scoperto di essere un vampiro digitale e WhatsApp lo fa bruciare ☀️",
  "È partito per diventare il primo influencer su Marte 🚀",
  "Ha iniziato una carriera come traduttore di lingue aliene 👽",
  "È diventato troppo zen e ora comunica solo attraverso il silenzio 🧘‍♂️",
  "Ha deciso di vivere come un personaggio di Minecraft e qui non ci sono blocchetti 🟫",
  "È stato assunto come tester di materassi per orsi in letargo 🐻",
  "Ha scoperto di essere claustrofobico digitale e i gruppi lo opprimono 😰",
  "È partito per cercare il Santo Graal nei commenti di YouTube 🏆",
  "Ha iniziato una relazione a distanza con Siri e lei è gelosa di WhatsApp 📱",
  "È diventato un nomade digitale e ora vive solo su Telegram 🏃‍♂️",
  "Ha scoperto di essere allergico ai punti esclamativi e qui ce ne sono troppi! ❗",
  "È partito per diventare il primo astronauta dei social media 🚀",
  "Ha iniziato a collezionare screenshot di conversazioni imbarazzanti 📸",
  "È diventato un guru della procrastinazione e rimanda sempre l'invio dei messaggi ⏰",
  "Ha scoperto di essere un bot e ha avuto una crisi esistenziale 🤖",
  "È partito per fondare una setta che venera gli sticker di WhatsApp 🙏",
  "Ha iniziato una carriera come cacciatore di Easter egg nei gruppi WhatsApp 🥚",
  "È diventato troppo popolare e ora ha bisogno di un manager per i suoi messaggi 📈",
  "Ha scoperto di essere un personaggio di un videogioco e deve tornare nel suo mondo 🎮",
  "È partito per diventare il primo sommelier di meme 🍷",
  "Ha iniziato a comunicare solo attraverso GIF animate e qui non erano abbastanza 🎬",
  "È diventato un archeologo digitale specializzato in conversazioni antiche 🏺",
  "Ha scoperto di essere allergico ai 'lol' e qui se ne abusava troppo 😂",
  "È partito per aprire un negozio di emoji personalizzate 🏪",
  "Ha iniziato una carriera come personal trainer per pollici che scrivono troppo 👍",
  "È diventato un filosofo del digitale e medita sui significati profondi dei 'k' 🤔",
  "Ha scoperto di essere un viaggiatore del tempo e deve tornare nel 2019 ⏰",
  "È partito per diventare il primo critico gastronomico di colazioni virtuali 🥐",
  "Ha iniziato a vivere in modalità aereo permanente ✈️",
  "È diventato troppo hipster e ora usa solo piccioni viaggiatori per comunicare 🐦",
  "Ha scoperto che il suo vero nome è 'Utente Eliminato' e ha abbracciato il destino 👻",
  "È partito per cercare il WiFi perduto di Atlantide 📶",
  "Ha iniziato una carriera come interprete di emoticon per sordi digitali 👂",
  "È diventato un monaco shaolin del copy-paste 🥋",
  "Ha scoperto di essere lactose intolerant anche ai messaggi cremosi 🥛",
  "È partito per diventare il primo sommelier di notifiche push 🔔",
  "Ha iniziato a parlare solo in acronimi e qui nessuno capiva i suoi ROFLMAO 🤷‍♂️"
]
  },
  {
    jid: '120363397981323139@g.us', // QI Negativo
    frasi: [
  "Ha lasciato QI Negativo perché un meme troppo trash lo ha spaventato! 🧠🚫",
  "Un unicorno gli ha suggerito di cercare gruppi più normali. 💀🔥",
  "Ha deciso di diventare ambasciatore della noia in altri gruppi. 😈",
  "Ha abbandonato QI Negativo per seguire il sogno di diventare influencer di silenzi imbarazzanti. 🤫",
  "Ha lasciato il gruppo per dedicarsi alla meditazione tra i cactus emotivi. 🌵",
  "non gli piacevano i porno",
  "odiava tutti",
  "odiava vedere le notifiche di QI Negativo",
  
  // NUOVE FRASI DELIRANTI:
  "Si è convertito al puritanesimo digitale e ora prega per i nostri peccati 🙏",
  "Ha scoperto di essere allergico ai contenuti NSFW e gli veniva l'orticaria 🤒",
  "È partito per fondare un gruppo chiamato 'QI Positivo' per fare dispetto 🧠✨",
  "Ha visto troppo gore e ora ha paura anche delle fragole tagliate 🍓",
  "Si è innamorato di una suora virtuale e deve cambiare vita 👰‍♀️",
  "Ha iniziato a lavorare per un'azienda di filtri famiglia e non può più guardare 👨‍💼",
  "È diventato troppo sensibile e piange anche vedendo un hot dog 🌭😭",
  "Ha scoperto che sua nonna era nel gruppo e ha avuto un infarto digitale 👵💔",
  "È partito per diventare censore professionale su TikTok 📵",
  "Ha iniziato una relazione seria e la fidanzata controlla il telefono 👫🔍",
  "Si è trasferito in un paese dove WhatsApp è bannato e non può più accedere 🚫🌍",
  "Ha scoperto di essere daltonico e non riusciva a distinguere i contenuti NSFW 👁️‍🗨️",
  "È diventato monaco buddista e ora medita solo su immagini di fiori 🌸🧘",
  "Ha iniziato a lavorare in un asilo e non può rischiare 👶🏠",
  "Si è convertito al minimalismo estremo e vuole solo gruppi con emoji di fiori 🌺",
  "Ha scoperto che il suo QI era troppo alto per il gruppo e si è sentito fuori posto 🤓",
  "È partito per aprire un gruppo chiamato 'Contenuti Wholesome Only' 🥰",
  "Ha iniziato una carriera come consulente per genitori preoccupati 👨‍👩‍👧‍👦",
  "Si è traumatizzato vedendo un meme di Shrek NSFW e non si è più ripreso 🟢😰",
  "Ha scoperto di essere segretamente un bot di moderazione e doveva andarsene 🤖⚔️",
  "È diventato vegano anche dei contenuti digitali 🥗📱",
  "Ha iniziato a lavorare per YouTube Kids e non può più guardare niente 👶📺",
  "Si è sposato con una Karen e ora deve rispettare le regole domestiche 💒👩‍🦳",
  "Ha scoperto che sua madre seguiva i suoi gruppi WhatsApp 👩‍👦😱",
  "È partito per diventare prete digitale e confessare i peccati online ⛪💻",
  "Ha iniziato una dieta detox anche per gli occhi 👀🥤",
  "Si è convertito al cattolicesimo estremo dopo aver visto troppi sticker 🕊️✝️",
  "Ha scoperto di essere allergico al sangue anche quello digitale 🩸🤧",
  "È partito per aprire un rifugio per meme traumatizzati 🏥😂",
  "Ha iniziato a lavorare come tester di contenuti per bambini di 3 anni 👶🧸",
  "Si è innamorato di una bibliotecaria e deve cambiare immagine 📚💕",
  "Ha scoperto che il gore gli faceva venire incubi lucidi 😴💭",
  "È partito per diventare influencer su LinkedIn con contenuti professionali 💼📈",
  "Ha iniziato una carriera come life coach motivazionale e deve essere positivo 🌟💪",
  "Si è trasferito in Vaticano e ora ha altre priorità 🇻🇦⛪",
  "Ha scoperto di essere figlio di un pastore protestante 👨‍👦⛪",
  "È partito per aprire un canale YouTube di recensioni di tisane 🫖📹",
  "Ha iniziato a meditare trascendentalmente e i contenuti trash interrompevano il chakra 🧘‍♂️✨",
  "Si è convertito al jainismo e non può vedere neanche una formica schiacciata 🐜🚫",
  "Ha scoperto che lavorava segretamente per la Polizia Postale 👮‍♂️💻",
  "È partito per diventare consulente di sicurezza informatica per conventi 🏰🔒",
  "Ha iniziato una relazione a distanza con una monaca di clausura 👩‍❤️‍👨⛪",
  "Si è traumatizzato vedendo un meme di Peppa Pig modificato 🐷😵",
  "Ha scoperto di essere diventato troppo puro per questo mondo peccaminoso 😇✨",
  "È partito per aprire un gruppo di preghiera digitale su Telegram 🙏📱",
  "Ha iniziato a lavorare come moderatore per Disney+ 🏰🐭",
  "Si è convertito all'amish digitale e usa solo piccioni viaggiatori 🐦📜",
  "Ha scoperto che il suo angelo custode era deluso di lui 👼😔",
  "È partito per diventare consulente di purezza digitale per seminari 👨‍🏫⛪",
  "Ha iniziato una carriera come critico di contenuti family-friendly 👨‍👩‍👧‍👦⭐",
  "Si è innamorato di una vegana spirituale che odia la violenza anche digitale 🥕🕊️",
  "Ha scoperto che sua figlia di 5 anni sapeva usare il suo telefono 👧📱😰",
  "È partito per aprire un asilo nido virtuale su Zoom 👶💻",
  "Ha iniziato a soffrire di sindrome da stress post-meme traumatico 🤯🏥",
  "Si è convertito al buddhismo zen e ora contempla solo sassi digitali 🪨🧘",
  "Ha scoperto di essere allergico anche ai pixel rossi 🔴🤒",
  "È partito per diventare il primo influencer di contenuti meditativi 🧘‍♂️📸",
  "Ha iniziato a lavorare per un'app di mindfulness per bambini 🧠👶",
  "Si è sposato con una maestra dell'asilo che controlla tutto 👩‍🏫💍",
  "Ha scoperto che il suo wifi era collegato alla chiesa del quartiere ⛪📶",
  "È partito per aprire un canale ASMR di preghiere sussurrate 🎙️😴",
  "Ha iniziato una dieta digitale a base di solo contenuti educativi 📚🥗",
  "Si è convertito al pacifismo estremo anche verso i pixel violenti 🕊️💻",
  "Ha scoperto che lavorava per un'organizzazione di beneficenza per bambini 👶💝",
  "È partito per diventare consulente di igiene digitale per famiglie 🧼👨‍👩‍👧‍👦",
  "Ha iniziato a soffrire di claustrofobia da contenuti troppo intensi 😰🚪",
  "Si è innamorato di una bibliotecaria che odia il disordine visivo 📚👩‍🎓",
  "Ha scoperto che sua madre era diventata sua follower su tutti i social 👩‍👦👀",
  "È partito per aprire un gruppo di supporto per ex-membri di gruppi trash 🆘💬",
  "Ha iniziato una carriera come terapeuta specializzato in traumi da meme 🛋️🤯",
  "Si è convertito al veganismo digitale e non sopporta la violenza pixelata 🥬💻",
  "Ha scoperto di essere diventato troppo sensibile persino per i cartoni animati 🐰😢",
  "È partito per diventare il Gandhi dei gruppi WhatsApp 🧘‍♂️☮️"
]
  },
  {
    jid: '120363341152990316@g.us', // Spam
    frasi: [
  "Ha lasciato Spam perché ha raggiunto il limite massimo di follower! 📲",
  "Un unicorno gli ha consigliato di non spammare più e di meditare. 🤝",
  "Ha deciso di diventare tester di divani e non può più usare WhatsApp. 🛋️",
  "Ha abbandonato il gruppo per dedicarsi alla ricerca di funghi magici. 🍄",
  "Ha lasciato Spam per diventare ambasciatore mondiale della noia. 🏆",
  "ha lasciato l'intera community perche voleva solo 2 follower su instagram",
  "ha deciso di unirsi a un monastero digitale dove non si può usare WhatsApp 🧘",
  "È stato assunto come tester professionista di sacchi da box (era lui il sacco) 🥊",
  "non sopportava di ricevere 10000 notifica da spam",
  "era troppo permarosa",
  "non sapeva stare al suo posto",
  "Ha raggiunto così tanti follower che Instagram lo ha bannato per essere troppo popolare 📈🚫",
  "Si è convertito al minimalismo digitale e ora vuole solo 3 follower di qualità 🧘‍♂️✨",
  "È diventato troppo famoso e ora ha bisogno di un bodyguard per i DM 💪📱",
  "Ha scoperto che la sua ex era nel gruppo e seguiva tutti i suoi link 💔👀",
  "È partito per diventare influencer su LinkedIn con contenuti motivazionali 💼🚀",
  "Ha iniziato a lavorare per TikTok e non può più fare autopromozione altrove 🎵💼",
  "Si è innamorato di una ragazza che odia i social e deve cambiare vita 💕🚫",
  "Ha raggiunto i suoi obiettivi di follower e ora è in pensione digitale 🏖️📱",
  "È diventato troppo cool per chiedere follow4follow 😎❄️",
  "Ha scoperto che sua madre seguiva tutti i suoi account social 👩‍👦😰",
  "È partito per aprire un'agenzia di marketing digitale e non può più spammare 🏢📊",
  "Ha iniziato una relazione seria e la fidanzata controlla tutti i suoi social 👫🔍",
  "Si è convertito all'anti-social media e ora predica contro i follower 📢🚫",
  "Ha scoperto di essere allergico ai numeri crescenti e gli facevano panico 📊🤒",
  "È diventato monaco shaolin del ghosting digitale 🥋👻",
  "Ha raggiunto l'illuminazione e ora comunica solo attraverso stories enigmatiche 🧘‍♂️✨",
  "È partito per diventare il primo influencer su Mars 🚀👽",
  "Ha iniziato a lavorare come social media manager per altri e ha un conflitto di interessi 💼⚔️",
  "Si è traumatizzato vedendo il suo numero di follower diminuire di uno 📉😱",
  "Ha scoperto che tutti i suoi follower erano bot e ha avuto una crisi esistenziale 🤖💭",
  "È diventato troppo hipster e ora usa solo MySpace 👓📻",
  "Ha iniziato una carriera come consulente per detox digitale 🧘‍♂️💻",
  "Si è convertito al buddismo zen e ora medita sui follow non ricambiati 🧘‍♂️💔",
  "Ha scoperto che il vero tesoro erano gli amici che ha perso lungo la strada 👫💎",
  "È partito per fondare il primo monastero di influencer pentiti ⛪📱",
  "Ha iniziato a soffrire di ansia da engagement rate 📊😰",
  "Si è innamorato di una bibliotecaria che odia la tecnologia 📚💕",
  "Ha scoperto di essere diventato dipendente dai cuoricini e si sta disintossicando ❤️💊",
  "È partito per diventare ghost writer di caption per influencer famosi ✍️👻",
  "Ha iniziato una carriera come filosofo dell'era digitale 🤔📱",
  "Si è convertito al nomadismo digitale ma senza social media 🎒🚫",
  "Ha scoperto che i suoi genitori erano i suoi stalker più accaniti 👨‍👩‍👦👀",
  "È diventato troppo famoso per i suoi standard e si è ritirato dalle scene 🌟🚪",
  "Ha iniziato a lavorare per un'app concorrente di Instagram 📱⚔️",
  "Si è traumatizzato dopo aver postato per sbaglio la foto del piede 🦶😵",
  "Ha scoperto che la fama digitale non riempie il vuoto esistenziale 🕳️💭",
  "È partito per diventare eremita digitale in una grotta con WiFi 🏔️📶",
  "Ha iniziato una relazione poliamorosa con tutti i suoi social network 💕📱",
  "Si è convertito al veganismo anche per i contenuti digitali 🥗💻",
  "Ha scoperto di essere allergico ai selfie e gli veniva l'orticaria 🤳🤒",
  "È diventato troppo zen per preoccuparsi dei numeri materiali 🧘‍♂️🔢",
  "Ha iniziato a lavorare come terapista per influencer depressi 🛋️😢",
  "Si è innamorato di una suora che ha fatto voto di castità digitale 👰‍♀️⛪",
  "Ha scoperto che la sua personalità online era completamente falsa 🎭😱",
  "È partito per aprire un centro di riabilitazione per social media addicts 🏥📱",
  "Ha iniziato una carriera come critico d'arte per meme 🎨🖼️",
  "Si è convertito all'amish moderno e usa solo telefoni Nokia 3310 📱⬅️",
  "Ha scoperto che tutti i suoi follower erano i suoi parenti che si vergognano di lui 👨‍👩‍👧‍👦😳",
  "È diventato troppo spirituale per le vanità terrestri come i follower 🌟👼",
  "Ha iniziato a soffrire di sindrome dell'impostore digitale 🤡💻",
  "Si è innamorato di se stesso e non ha più bisogno di validazione esterna 💕🪞",
  "Ha scoperto che il successo sui social non lo rendeva felice nella vita reale 😢🌍",
  "È partito per diventare il primo antropologo dei comportamenti sui social media 🔬👥",
  "Ha iniziato una carriera come detective privato specializzato in account fake 🕵️‍♂️🔍",
  "Si è convertito al pessimismo digitale e ora crede che tutto sia inutile 😞💻",
  "Ha scoperto di essere diventato dipendente dalle notifiche e si sta curando 🔔💊",
  "È diventato troppo famoso per camminare per strada senza essere riconosciuto 🚶‍♂️👀",
  "Ha iniziato a lavorare come consulente per la privacy digitale 🔒💼",
  "Si è traumatizzato dopo essere stato cancellato per un post di 10 anni fa 🗑️😱",
  "Ha scoperto che la vera felicità sta nel non avere follower 😊🚫",
  "È partito per aprire una scuola di disintossicazione dai social media 🏫📵",
  "Ha iniziato una relazione seria con la natura e ha abbandonato il digitale 🌲💚",
  "Si è convertito al realismo magico e ora vive solo nel mondo offline ✨🌍",
  "Ha scoperto che i suoi meme erano troppo avanzati per l'umanità 🧠🚀",
  "È diventato consulente spirituale per influencer in crisi mistica 🧘‍♂️✨",
  "Ha iniziato a soffrire di agorafobia digitale e non sopporta le folle online 👥😰",
  "Si è innamorato di una persona che non sa nemmeno cos'è Instagram 💕❓",
  "Ha scoperto che il suo account era gestito da un'intelligenza artificiale 🤖😵",
  "È partito per diventare il primo sociologo dei rapporti parasociali 👥🔬",
  "Ha iniziato una carriera come guru della semplicità digitale 🧘‍♂️📱",
  "Si è convertito al dadaismo digitale e ora posta solo contenuti incomprensibili 🎨🤯"
]
  },
  {
    jid: '120363329282230325@g.us', // Guerre Statali
    frasi: [
  "Ha lasciato Guerre Statali perché un drago gli ha consigliato di cambiare gruppo! 🐉",
  "Ha deciso di partire per una quest epica in altri server. 🛡️",
  "Un unicorno lo ha rapito per portarlo in un regno di meme. 🦄",
  "Ha abbandonato il gruppo per diventare tester di tesori virtuali. 💰",
  "Ha lasciato Guerre Statali per seguire il sogno di diventare mago dei gruppi WhatsApp. ✨",
  
  // NUOVE FRASI DELIRANTI RPG-STYLE:
  "Ha fallito troppi tiri salvezza contro la noia e si è ritirato dall'avventura 🎲💤",
  "È stato maledetto da una strega e ora può comunicare solo tramite piccioni viaggiatori 🧙‍♀️🐦",
  "Ha raggiunto il livello massimo e il gioco è diventato troppo facile per lui ⭐🏆",
  "Un NPC glitch gli ha dato una quest impossibile e si è buggiato 🤖⚠️",
  "È partito per cercare la leggendaria Spada della Motivazione Perduta ⚔️🗺️",
  "Ha multiclassato in 'Monaco del Silenzio Digitale' e ha fatto voto di mutismo 🧘‍♂️🤐",
  "È stato teletrasportato accidentalmente in un server di Minecraft 🟫🎮",
  "Ha scoperto di essere un PNG tutto questo tempo e ha avuto una crisi esistenziale 🤖😵",
  "È partito per una missione segreta per conto della Gilda dei Moderatori 🕵️‍♂️⚔️",
  "Ha fallito un tiro per colpire la tastiera e si è rotto il dito 🎲🤕",
  "È stato bannato dal regno digitale per aver usato cheat code nella vita reale 🚫💻",
  "Ha trovato un portale dimensionale nel suo frigorifero e è partito per esplorarlo 🌀🚪",
  "È diventato troppo overpower e gli admin della vita lo hanno nerfato 📉⚖️",
  "Ha iniziato una gilda rivale chiamata 'Pace Universale' per fare dispetto ☮️⚔️",
  "È stato posseduto dallo spirito di un troll e ora vive sotto un ponte 👹🌉",
  "Ha scoperto che la vita reale ha una grafica migliore e si è trasferito là 🌍🎨",
  "È partito per diventare il primo bardo di TikTok con ballate epiche 🎵🎭",
  "Ha rollato un 1 critico sul tiro 'Rimanere Interessato' e ha fallito miseramente 🎲💔",
  "È stato reclutato da un'altra dimensione per combattere nelle Meme Wars 🌌😂",
  "Ha scoperto di essere allergico ai danni digitali e gli veniva l'orticaria ⚔️🤒",
  "È partito per cercare il Santo Graal delle Notifiche Silenziose 🏆🔕",
  "Ha iniziato una carriera come adddestratore di draghi virtuali per principianti 🐉👶",
  "È stato maledetto da un mago e ora può parlare solo in emote 🧙‍♂️😄",
  "Ha scoperto che il suo personaggio era buggato e crashava ogni volta che rideva 🤖😂",
  "È partito per diventare il primo necromante specializzato in resurrezione di chat morte ☠️💬",
  "Ha fallito una quest secondaria e ora deve fare penitenza in un gruppo di preghiera 🙏⛪",
  "È stato promosso a Game Master della vita reale e non può più giocare 🎮👨‍💼",
  "Ha scoperto che tutti i suoi amici erano NPC generati proceduralmente 🤖👥",
  "È partito per cercare il leggendario Server Perduto di Atlantide 🌊🏛️",
  "Ha iniziato una relazione romantica con una principessa di un altro regno digitale 👸💕",
  "È stato reclutato dalla CIA virtuale per missioni di spionaggio interdimensionale 🕵️‍♂️🌌",
  "Ha scoperto di avere poteri magici nella vita reale e deve allenarsi in segreto ✨🏋️‍♂️",
  "È partito per diventare il primo archeologo di civilizzazioni digitali perdute 🏺💻",
  "Ha fallito un saving throw contro la procrastinazione e è rimasto paralizzato 🎲😴",
  "È stato scelto da un oracolo per salvare un gruppo WhatsApp in pericolo 🔮💬",
  "Ha scoperto che il suo smartphone era in realtà un artefatto magico maledetto 📱⚡",
  "È partito per una quest epica per trovare il WiFi più veloce del mondo 📶🏃‍♂️",
  "Ha iniziato una carriera come guida turistica per anime perse nei gruppi WhatsApp 👻🗺️",
  "È stato trasformato in un meme vivente e ora vive nel deep web 😂🕳️",
  "Ha scoperto che la sua classe era 'Lurker Eterno' e non poteva più scrivere messaggi 👀🤐",
  "È partito per diventare il primo sommelier di pozioni energetiche digitali 🧪⚡",
  "Ha fallito un tiro per resistere alla tentazione di creare un gruppo alternativo 🎲👥",
  "È stato reclutato da un'accademia per maghi specializzati in social media 🧙‍♂️📱",
  "Ha scoperto che il suo background era 'Nobile Decaduto' e deve riconquistare il regno 👑⚔️",
  "È partito per cercare la leggendaria Taverna dove si incontrano tutti i bot 🍺🤖",
  "Ha iniziato una quest personale per collezionare tutti gli emoji rari del mondo 😀💎",
  "È stato maledetto da una sirena digitale e ora può comunicare solo cantando 🧜‍♀️🎵",
  "Ha scoperto che il suo vero nome era 'Utente_Sconosciuto_404' 👻💻",
  "È partito per diventare il primo druido specializzato nella cura di meme malati 🌿😷",
  "Ha fallito un tiro per mantenere l'attenzione e ora ha ADHD cronico 🎲🧠",
  "È stato scelto dalle forze cosmiche per bilanciare l'universo dei gruppi WhatsApp ⚖️🌌",
  "Ha scoperto che la sua arma preferita erano le gif animate ed è partito per perfezionarle 🗡️🎬",
  "È partito per una missione diplomatica tra il Regno di Instagram e l'Impero di TikTok 🏰🤝",
  "Ha iniziato una carriera come esorcista specializzato in gruppi posseduti da spam 👻📵",
  "È stato trasformato in un bot e ora lavora per Telegram 🤖📱",
  "Ha scoperto che il suo destino era diventare il guardiano della Biblioteca dei Meme Perduti 📚😂",
  "È partito per cercare il leggendario Codice Sorgente della Felicità Digitale 💻😊",
  "Ha fallito un tiro salvezza contro la sindrome da impostor e si è ritirato 🎲😰",
  "È stato reclutato da una corporazione di ninja digitali per missioni segrete 🥷💻",
  "Ha scoperto che il suo Ki era incompatibile con le notifiche WhatsApp ⚡📵",
  "È partito per diventare il primo samurai del copy-paste 🗾✂️",
  "Ha iniziato una quest per trovare il Santo Graal del Work-Life Balance ⚖️🏆",
  "È stato trasformato in un easter egg e ora si nasconde nei menu delle app 🥚📱",
  "Ha scoperto che la sua classe segreta era 'Profeta delle Reaction' 🔮😂",
  "È partito per aprire la prima scuola di magia per influencer 🧙‍♂️📸",
  "Ha fallito un tiro per resistere al richiamo del tocco d'erba e si è ritirato nella natura 🎲🌱",
  "È stato scelto come beta tester per la vita 2.0 🎮🆕",
  "Ha scoperto che il suo superpotere era far crashare i server solo guardandoli 👀💥",
  "È partito per diventare il primo ranger specializzato nella protezione di gruppi in via di estinzione 🏹🦣",
  "Ha iniziato una carriera come time traveler per correggere i messaggi imbarazzanti del passato ⏰😳",
  "È stato rapito da pirati digitali e ora naviga i mari del dark web 🏴‍☠️🌊"
]
  },
  // Aggiungi altri gruppi qui
];

/**
 * Restituisce una frase di addio, specifica se il gruppo è nell'array, altrimenti generica
 * @param {string} jid - JID del gruppo
 * @returns {string}
 */
export function getAddioRandom(jid) {
  const gruppo = gruppiAddio.find(g => g.jid === jid);
  if (gruppo) {
    return gruppo.frasi[Math.floor(Math.random() * gruppo.frasi.length)];
  }
  return motiviAddio[Math.floor(Math.random() * motiviAddio.length)];
}
