// Frasi di benvenuto generiche
export const frasiBenvenuto = [
    "_Benvenuto! Sei il visitatore numero 1.000.000! (Mentiamo sempre sui numeri) 🎉_",
    "_Attenzione: questo gruppo può causare dipendenza e risate incontrollabili ⚠️_",
    "_Sei appena entrato nel miglior gruppo di sempre... o almeno così ci piace pensare 🤪_",
    "_Benvenuto! Abbiamo biscotti virtuali e caffè immaginario ☕_",
    "_Ecco un nuovo membro da aggiungere alla nostra collezione di stranezze 🧩_",
    "_Benvenuto! Le tue credenziali sono state registrate nel nostro database segreto... scherzo (forse) 👾_",
    "_Sei entrato nel momento sbagliato, stavamo parlando male di te... ah no, non ti conoscevamo ancora 😈_",
    "_Benvenuto! Qui l'unica regola è che non ci sono regole... a parte tutte quelle che abbiamo 📜_",
    "_Congratulazioni! Hai appena vinto un viaggio tutto pagato! Scherzo, sei solo in un gruppo WhatsApp ✈️_",
    "_Benvenuto! Sei più un tipo da gif, meme o messaggi vocali? 🎭_",
    "_Ehilà! Sei qui per la riunione segreta degli illuminati o per sbaglio? 👁️_",
    "_Benvenuto! Il nostro gruppo è come una scatola di cioccolatini: non sai mai cosa ti capita 🍫_",
    "_Salve! Ti avviso che qui dentro perdiamo tutti almeno il 50% del QI giornalmente 🧠_",
    "_Benvenuto! Sei pronto a perdere la tua dignità un messaggio alla volta? 😏_",
    "_Ciao nuovo! Sei qui per la festa a sorpresa? Che stupido, te l'ho rovinata 🎂_",
    "_Benvenuto! Sei l'elemento casuale che mancava al nostro caos organizzato 🌀_",
    "_Eccoti! Stavo giusto pensando che mancava qualcuno da bullizzare... ehm, accogliere 🤗_",
    "_Salve viaggiatore! Hai portato con te provviste per sopravvivere a questo gruppo? 🎒_",
    "_Benvenuto! Sei più forte di quanto sembri se hai deciso di entrare qui 💪_",
    "_Ciao! Sei qui per caso o perché tutti gli altri gruppi ti hanno bannato? 🚫_",
    "_Benvenuto! Il nostro gruppo è come un bonsai: richiede cure costanti e nessuno sa davvero come si fa 🌱_",
    "_Benvenuto! Sei l'ultimo arrivato, quindi secondo la tradizione paghi la pizza virtuale 🍕"
];

// Gruppi con benvenuto specifico
export const gruppiBenvenuto = [
  {
    jid: '120363401630273537@g.us', // Viridi Celesti
    frasi: [
      "Benvenuto su Viridi Celesti! 🌟\nPrima di iniziare, leggi tutte le regole: niente limiti di età, niente obbligo di presentarsi, ma rispetto e buon senso sono fondamentali.",
      "Sei entrato in Viridi Celesti, qui si fa la storia! 🏆\nRicorda: 🔴 no voip, 🔴 no contenuti osceni, 🟡 no troll, 🟡 non scrivere in privato, 🟡 no spam/flood, 🔴 no pubblicità/link di altri gruppi. Leggi !gruppo per i comandi!",
      "Viridi Celesti ti accoglie tra i migliori! 💚\nAbbiamo creato il ruolo mod, diverso dagli admin. Scrivi !mods per vedere la lista. Non chiedere l'admin, saremo noi a contattarti! Discord: https://discord.gg/Sewntrqxrn",
      "🌱 Qui si cresce insieme, ma solo se rispetti le regole!",
      "🎉 Sei il nuovo elemento del nostro caos organizzato. Benvenuto!",
      "🟢 Azioni consentite: divertirsi, chiacchierare, fare amicizia!",
      "🔴 Rischi il ban se non rispetti le regole, ma se sei qui sei già sulla buona strada!",
      "🟡 Se hai dubbi, chiedi ai mod o agli admin. Siamo qui per aiutarti!",
      "💬 Presentati se vuoi, ma non è obbligatorio. Sii te stesso!",
      "📜 Le regole sono poche ma importanti. Leggile e goditi il gruppo!",
      "🤗 Qui nessuno viene bullizzato, solo accolto con un sorriso!",
      "🧩 Ogni membro è un pezzo unico della nostra community!",
      "🍕 Secondo la tradizione, l'ultimo arrivato paga la pizza virtuale!",
      "💫 Benvenuto nella dimensione più green di WhatsApp!",
      "🌿 Stai per entrare in un ecosistema di menti brillanti!",
      "🎭 Qui puoi essere te stesso, ma ricorda: il rispetto è sacro!",
      "🏰 Sei appena entrato nel regno più civilizzato dei gruppi!",
      "⚡ Preparati a vivere conversazioni epiche e momenti indimenticabili!",
      "🎨 Questo gruppo è un'opera d'arte e tu sei il nuovo pennello!",
      "🌊 Lasciati trasportare dalla corrente positiva di Viridi Celesti!",
      "🚀 Destinazione: divertimento infinito. Allaccia le cinture!",
      "🔮 Il futuro qui è sempre verde e luminoso come il nostro nome!",
      "🎪 Benvenuto nel circo più educato del mondo digitale!",
      "🌈 Ogni colore dell'arcobaleno è benvenuto, purché rispetti i verdi!",
      "🏆 Hai appena vinto il biglietto per il gruppo più esclusivo!",
      "🎵 La melodia della community suona più bella con la tua voce!",
      "🗝️ Hai trovato la chiave segreta per entrare tra i Viridi!",
      "🌺 Fiorirai qui dentro come un fiore in primavera!",
      "🎯 Obiettivo raggiunto: sei ufficialmente un Viridi Celeste!",
      "🌙 Anche di notte, questo gruppo brilla di luce propria!",
      "⭐ Sei la nuova stella nella costellazione Viridi!",
      "🎈 Il tuo arrivo è una festa che merita palloncini virtuali!",
      "🏖️ Rilassati, qui l'atmosfera è sempre vacanziera ma rispettosa!",
      "🎧 Sintonizzati sulla frequenza Viridi: 100% buone vibrazioni!",
      "🌅 Ogni nuovo giorno qui inizia con un nuovo amico come te!",
      "🎊 Confetti digitali per celebrare il tuo ingresso!",
      "🌸 La primavera è arrivata: hai portato aria fresca nel gruppo!",
      "🎮 Benvenuto nel multiplayer più friendly dell'universo!",
      "🔥 Il tuo arrivo ha acceso una nuova scintilla nella chat!",
      "🌍 Hai appena scoperto un nuovo continente: Viridilandia!",
      "🎬 Luci, camera, azione! Il tuo spettacolo su Viridi inizia ora!",
      "🎨 Sei il nuovo colore nella palette perfetta di questo gruppo!",
      "🎭 Qui ogni giorno è un nuovo atto di una commedia fantastica!",
      "🌱 Piantiamo insieme i semi di nuove amicizie!",
      "🏅 Medaglia d'oro per aver scelto il gruppo giusto!",
      "🎪 Signore e signori, ecco a voi il nuovo artista del circo Viridi!",
      "🌺 Il giardino Viridi ha un nuovo fiore speciale!",
      "🎨 Hai aggiunto un tocco di classe alla nostra galleria!",
      "🌊 Surfeggia sulle onde di positività che troverai qui!",
      "🎯 Centro! Hai colpito nel segno scegliendo questo gruppo!",
      "🌙 Dolci sogni digitali ti aspettano in questa community!",
      "⚡ Preparati a essere folgorato dalla bellezza di Viridi Celesti!",
      "🎈 Il tuo umore volerà alto come un palloncino in questo gruppo!",
      "🏰 Benvenuto nella corte reale più democratica del web!",
      "🌈 Dopo la tempesta c'è sempre l'arcobaleno Viridi!",
      "🎵 La sinfonia del gruppo suona più armoniosa con te!",
      "🔮 La palla di cristallo dice: qui troverai felicità!",
      "🌸 Sboccerai come un fiore di ciliegio in questo ambiente!",
      "🎬 Il tuo film preferito? 'Avventure su Viridi Celesti'!",
      "🌅 L'alba di una nuova amicizia inizia proprio ora!",
      "🎊 Party time! Il tuo arrivo merita una celebrazione!",
      "🌍 Benvenuto nel paradiso terrestre dei gruppi WhatsApp!",
      "🎮 Achievement unlocked: sei entrato nella elite Viridi!",
      "🔥 Il termometro dell'energia del gruppo è appena salito!"
    ]
  },
  {
    jid: '120363397981323139@g.us', // qi negativo
    frasi: [
      "Benvenuto in QI Negativo! 🧠🚫 Qui puoi sfogarti con materiale porno/gore, ma è vietato qualsiasi contenuto pedo. Rispetta i limiti!",
      "Attenzione: gruppo vietato ai deboli di cuore! Qui puoi mandare ciò che su Viridi Celesti sarebbe da ban, tranne pedo. Leggi le regole e non esagerare! 💀🔥",
      "Sei in QI Negativo, il posto dove puoi essere te stesso senza filtri (ma niente pedo). Se hai dubbi, chiedi ai mod!",
      "😈 Qui puoi dire quello che vuoi, ma ricorda: il rispetto non è mai fuori moda!",
      "💀 Se non sopporti il gore, meglio restare su Viridi Celesti!",
      "🚫 Materiale pedo = ban immediato. Non rischiare!",
      "🔥 Sfogati, ridi, scherza, ma non superare i limiti della decenza!",
      "🧠 Qui il QI scende, ma il divertimento sale!",
      "👾 Se hai bisogno di aiuto, i mod sono sempre disponibili!",
      "🎭 Non giudichiamo nessuno, ma chi sbaglia paga!",
      "📢 Se vuoi segnalare qualcosa, scrivi agli admin!",
      "🦾 Sii te stesso, ma non dimenticare le regole!",
      "🎲 Ogni giorno è una nuova sfida, accettala!",
      "🌋 Benvenuto nel vulcano delle emozioni estreme!",
      "🎪 Il circo degli orrori digitali ti dà il benvenuto!",
      "💣 Preparati a esplodere di risate (e forse anche di disgusto)!",
      "🔞 Zona riservata ai maggiorenni mentalmente instabili!",
      "🎭 Qui le maschere cadono e la verità emerge!",
      "🌪️ Entra nel tornado del trash più epico del web!",
      "🔥 Questo gruppo è come l'inferno, ma con WiFi gratis!",
      "🎢 Montagne russe emotive garantite!",
      "👹 Libera il demone che è in te (ma con classe)!",
      "🌑 Benvenuto nel lato oscuro della forza digitale!",
      "⚠️ Attenzione: questo gruppo può causare dipendenza da trash!",
      "🎯 Hai trovato il bersaglio perfetto per la tua follia!",
      "🌪️ Preparati al caos controllato più divertente del pianeta!",
      "💀 Qui i deboli di stomaco diventano forti o scappano!",
      "🎊 Festa del cattivo gusto! Tutti invitati!",
      "🔮 La palla di cristallo dice: qui troverai il tuo lato dark!",
      "🎮 Hai unlocked la modalità 'Senza Censure'!",
      "🌈 Anche l'arcobaleno ha un lato nero... eccolo!",
      "🎪 Benvenuto nel freakshow più educato del web!",
      "🌋 Lava emotiva in arrivo! Prepara l'elmetto!",
      "🎭 Teatro dell'assurdo: tutti gli attori sono pazzi!",
      "💣 Bomba di contenuti esplosivi in arrivo!",
      "🔥 Brucerai dalla curiosità di vedere cosa succede qui!",
      "⚡ Preparati a essere folgorato da contenuti shock!",
      "🎢 Il roller coaster del trauma inizia ora!",
      "🌑 Eclipse totale del buon gusto in corso!",
      "🎯 Centro! Hai colpito il gruppo più estremo!",
      "👾 Modalità boss attivata: sopravvivrai al QI Negativo?",
      "🔮 Benvenuto nella dimensione parallela del trash!",
      "🌪️ Ciclone di follia in arrivo! Tieniti forte!",
      "💀 Cimitero del politically correct! R.I.P. buone maniere!",
      "🎊 Party hard con contenuti harder!",
      "🌋 Eruzione di contenuti molten-trash garantita!",
      "🎭 Commedia nera? No, tragedia colorata!",
      "⚠️ Pericolo: zona ad alto tasso di WTF!",
      "🔥 Il purgatorio digitale ti accoglie a braccia aperte!",
      "🎮 Hai sbloccato il livello inferno del divertimento!",
      "🌈 Fifty shades of trash ti aspettano!",
      "💣 Preparati all'esplosione nucleare di contenuti!",
      "🎪 Circo Barnum del digitale: ogni mostro è benvenuto!",
      "⚡ High voltage content zone! Attento alle scosse!",
      "🌑 Welcome to the dark side... we have memes!",
      "🎯 Jackpot! Hai trovato la slot machine del chaos!",
      "🔮 Il dado è tratto: sei ufficialmente un QI Negativo!",
      "🌪️ Hurricane trash categoria 5 in arrivo!",
      "💀 Necropoli del buon senso: benvenuto tra i morti viventi!",
      "🎊 Rave party nel cimitero delle convenzioni sociali!",
      "🌋 Vesuvio 2.0: eruzione di contenuti garantita!",
      "🎭 Shakespeare ha scritto Amleto, noi scriviamo trash-letto!"
    ]
  },
  {
    jid: '120363341152990316@g.us', // Spam
    frasi: [
      "Benvenuto su Spam! 📲 Qui puoi condividere IG/TikTok e ricambiare i follow. È l'unico gruppo dove questa pratica è consentita!",
      "Spam: promuovi solo i tuoi social, niente pubblicità a siti, servizi, vendita o link di altri gruppi WhatsApp. Non esagerare con lo spam! 🚫",
      "Qui si spamma solo per i social, niente spam commerciale o pubblicità. Se vuoi vedere le regole, chiedi agli admin!",
      "🔗 Vietato spammare link di altri gruppi, canali o piattaforme!",
      "📈 Qui puoi crescere su IG e TikTok, ma niente pubblicità a pagamento!",
      "🤝 Ricambia sempre il follow, è la regola d'oro!",
      "🚫 Non si vendono servizi o prodotti, solo social!",
      "🟡 Se hai dubbi sulle regole, chiedi agli admin!",
      "🎉 Ogni nuovo membro porta nuovi social da scoprire!",
      "💬 Puoi presentarti, ma non è obbligatorio!",
      "🧩 Siamo una community di creator, non di venditori!",
      "📜 Le regole sono semplici: rispetto e niente spam commerciale!",
      "🍕 L'ultimo arrivato paga la pizza virtuale anche qui!",
      "🚀 Preparati a decollare verso la fama digitale!",
      "⭐ Sei la nuova stella nascente del nostro universo social!",
      "📸 Snap! Hai appena immortalato il momento perfetto entrando qui!",
      "🎬 Luci, camera, follow! Il tuo show inizia ora!",
      "🌟 Brilla come un influencer, cresci come un professionista!",
      "📱 Il tuo smartphone ringrazierà per tutti i nuovi follower!",
      "🎯 Target centrato: hai trovato il gruppo giusto per crescere!",
      "🌈 Ogni colore del tuo feed sarà più bello con i nostri follow!",
      "🎪 Benvenuto nel circus dei creator più etici del web!",
      "🏆 Premio per il miglior nuovo arrivato! (Virtuale, ovviamente)",
      "🎨 Dipingi il tuo successo con i colori dei social media!",
      "🚀 Missione: raggiungere le stelle dei follower! Avviata!",
      "⚡ Velocità della luce nei follow garantita!",
      "🎵 La musica del successo suona meglio con più follower!",
      "🔥 Il tuo contenuto sta per incendiare i social!",
      "🌊 Surfa sull'onda del successo digitale!",
      "🎮 Hai unlocked il level 'Crescita Social'!",
      "🌺 Sboccerai come un fiore su Instagram!",
      "🎈 Il tuo ego volerà alto come un palloncino!",
      "🏖️ Vacanza permanente dalla preoccupazione dei follower!",
      "🎊 Party time! Ogni nuovo follow è una festa!",
      "🌙 Anche di notte, i tuoi social brilleranno!",
      "🎯 Bullseye! Hai colpito nel segno della crescita!",
      "🔮 Il futuro dice: follower in arrivo!",
      "🌸 Primavera digitale: tempo di nuove fioriture social!",
      "🎬 Regista della tua fama: azione!",
      "⭐ Hollywood può aspettare, prima conquista Instagram!",
      "🚀 NASA chiamare base: nuovo influencer in orbita!",
      "🎨 Sei il Picasso dei contenuti social!",
      "🌈 Arcobaleno di possibilità ti aspetta!",
      "🎪 Il greatest show on earth? Il tuo profilo!",
      "🔥 Preparati a bruciare le classifiche dei trending!",
      "⚡ Thunder struck! Sei entrato nel gruppo giusto!",
      "🌊 Tsunami di follower in arrivo!",
      "🎯 Archery master del social marketing!",
      "🏆 Champions League dei creator: sei qualificato!",
      "🌟 Stella polare del successo digitale!",
      "🎬 Oscar per il miglior newcomer sui social!",
      "🚀 SpaceX dei social media: destinazione successo!",
      "⭐ Walk of fame digitale: la tua stella ti aspetta!",
      "🎨 Van Gogh dei post: capolavori in arrivo!",
      "🌈 Somewhere over the rainbow... ci sono i tuoi follower!",
      "🎪 Barnum dei social: every follower tells a story!",
      "🔥 Phoenix del digitale: risorgerai più forte!",
      "⚡ Flash! Velocità della luce nella crescita!",
      "🌊 Captain of the social seas!",
      "🎯 Robin Hood dei follow: rubi ai ricchi per dare ai poveri!",
      "🏆 Gladiator dell'arena digitale!",
      "🌟 North star del successo online!"
    ]
  },
  {
    jid: '120363329282230325@g.us', // guerre statali
    frasi: [
      "Benvenuto in Guerre Statali! ⚔️🕒 Qui puoi usare i comandi RPG del bot a qualsiasi orario, senza limiti!",
      "Guerre Statali: il regno dei comandi RPG, sempre attivi per la tua battaglia! Ricorda di rispettare le regole generali del bot! 🛡️",
      "Sei pronto a combattere? In Guerre Statali puoi giocare con i comandi RPG quando vuoi! Se hai dubbi, chiedi ai mod o agli admin.",
      "⚔️ Qui la battaglia non si ferma mai, preparati!",
      "🛡️ Rispetta le regole e il gioco sarà più divertente per tutti!",
      "🎲 Puoi sfidare chi vuoi, quando vuoi!",
      "🟢 Azioni consentite: giocare, sfidare, divertirsi!",
      "🔴 Vietato barare o disturbare gli altri giocatori!",
      "🟡 Se hai dubbi sulle regole RPG, chiedi ai mod!",
      "🎉 Ogni nuovo membro è un potenziale campione!",
      "💬 Presentati se vuoi, ma non è obbligatorio!",
      "🧩 Ogni giocatore è importante per la community!",
      "🍕 Anche qui, l'ultimo arrivato paga la pizza virtuale!",
      "💡 Prova i plugin RPG: .caccia per cacciare mostri, .shop per comprare oggetti, .inventario per vedere il tuo equipaggiamento!",
      "🪙 Usa .wallet o .portafoglio per vedere i tuoi dolci e monete!",
      "🏠 Con .casa puoi gestire la tua dimora virtuale!",
      "🗺️ Esplora dungeon con .esplora o .dungeon!",
      "👨‍👩‍👧‍👦 Scopri la tua famiglia RPG con .famiglia e .alberofamiliare!",
      "💰 Trasferisci monete con .pay o .transfer!",
      "🛒 Compra e vendi oggetti con .shop, .compra, .vendi!",
      "🔋 Cura i tuoi personaggi con .cura o .heal!",
      "🔨 Prova .scassa per rompere oggetti e trovare tesori!",
      "📈 Sali di livello con .levelup e controlla il tuo livello con .livello!",
      "🏰 Benvenuto nel regno più epico del gaming digitale!",
      "⚔️ Affila la spada e prepara lo scudo: l'avventura inizia!",
      "🐉 I draghi aspettano solo te per essere sconfitti!",
      "🏆 La gloria eterna ti attende sul campo di battaglia!",
      "⚡ Poteri magici illimitati, ma usa il cervello!",
      "🌟 Sei la nuova leggenda che stavamo aspettando!",
      "🎮 Game mode: EPIC attivato!",
      "🗡️ La tua spada virtuale scintilla di potere!",
      "🛡️ La difesa migliore è un buon attacco... e rispetto!",
      "🏹 Arciere o guerriero? Qui puoi essere entrambi!",
      "🧙‍♂️ Benvenuto nella gilda dei maghi più potenti!",
      "⚔️ Duelli all'alba? No, duelli 24/7!",
      "🏰 Il castello delle avventure ti apre le porte!",
      "🎯 Mira precisa richiesta per vincere le guerre!",
      "🔥 Il fuoco della battaglia arde nei tuoi occhi!",
      "❄️ Freddo come il ghiaccio, caldo come la lava!",
      "⚡ Veloce come un fulmine, forte come un gigante!",
      "🌪️ Turbine di azione e divertimento garantito!",
      "🎪 Il circo dei gladiatori digitali ti accoglie!",
      "🏆 Sei il prescelto per vincere tutte le guerre!",
      "⭐ Stella nascente dell'arena virtuale!",
      "🎬 Il tuo film d'azione personale inizia ora!",
      "🚀 Razzo verso la vittoria pronto al decollo!",
      "🌈 Arcobaleno di possibilità strategiche!",
      "🎊 Festa di benvenuto per il nuovo campione!",
      "🌙 Anche di notte, le guerre non dormono mai!",
      "🔮 Il destino dice: vittoria assicurata!",
      "🌸 Sboccerai come un samurai in primavera!",
      "🎭 Commedia o tragedia? Tu scegli il finale!",
      "⚔️ Gladiator della tastiera, spadaccino del mouse!",
      "🏰 Benvenuto nella Tavola Rotonda 2.0!",
      "🐉 Dragon slayer in training, reporting for duty!",
      "🏹 Legolas digitale pronto per l'azione!",
      "🛡️ Capitan America del gaming online!",
      "⚡ Thor del thunder digitale!",
      "🔥 Ghost Rider delle guerre virtuali!",
      "❄️ Elsa ma con la spada invece della magia!",
      "🌪️ Tornado di skill in arrivo!",
      "🎮 Player One della vita reale!",
      "🏆 MVP della community in arrivo!",
      "⭐ All Star del gaming digitale!",
      "🎬 Protagonista del blockbuster 'Guerre Statali'!",
      "🚀 Astronauta delle galassie virtuali!"
    ]
  },
  // Aggiungi altri gruppi qui
];

/**
 * Restituisce una frase di benvenuto, specifica se il gruppo è nell'array, altrimenti generica
 * @param {string} jid - JID del gruppo
 * @returns {string}
 */
export function getBenvenutoRandom(jid) {
  const gruppo = gruppiBenvenuto.find(g => g.jid === jid);
  if (gruppo) {
    return gruppo.frasi[Math.floor(Math.random() * gruppo.frasi.length)];
  }
  return frasiBenvenuto[Math.floor(Math.random() * frasiBenvenuto.length)];
}
