// Array frasi di benvenuto
export const frasiBenvenuto = [
    "_Benvenuto! Sei il visitatore numero 1.000.000! (Mentiamo sempre sui numeri) 🎉_",
    "_Attenzione: questo gruppo può causare dipendenza e risate incontrollabili ⚠️_",
    "_Sei appena entrato nel miglior gruppo di sempre... o almeno così ci piace pensare 🤪_",
    "_Benvenuto! Abbiamo biscotti virtuali e caffè immaginario ☕_",
    "_Ecco un nuovo membro da aggiungere alla nostra collezione di stranezze 🧩_",
    "_Benvenuto! Le tue credenziali sono state registrate nel nostro database segreto... scherzo (forse) 👾_",
    "_Sei entrato nel momento sbagliato, stavamo parlando male di te... ah no, non ti conoscevamo ancora 😈_",
    "_Benvenuto! Qui l'unica regola è che non ci sono regole... a parte tutte quelle che abbiamo 📜_",
    "_Congratulazioni! Hai appena vinto un viaggio tutto pagato! Scherzo, sei solo in un gruppo WhatsApp ✈️_",
    "_Benvenuto! Sei più un tipo da gif, meme o messaggi vocali? 🎭_",
    "_Ehilà! Sei qui per la riunione segreta degli illuminati o per sbaglio? 👁️_",
    "_Benvenuto! Il nostro gruppo è come una scatola di cioccolatini: non sai mai cosa ti capita 🍫_",
    "_Salve! Ti avviso che qui dentro perdiamo tutti almeno il 50% del QI giornalmente 🧠_",
    "_Benvenuto! Sei pronto a perdere la tua dignità un messaggio alla volta? 😏_",
    "_Ciao nuovo! Sei qui per la festa a sorpresa? Che stupido, te l'ho rovinata 🎂_",
    "_Benvenuto! Sei l'elemento casuale che mancava al nostro caos organizzato 🌀_",
    "_Eccoti! Stavo giusto pensando che mancava qualcuno da bullizzare... ehm, accogliere 🤗_",
    "_Salve viaggiatore! Hai portato con te provviste per sopravvivere a questo gruppo? 🎒_",
    "_Benvenuto! Sei più forte di quanto sembri se hai deciso di entrare qui 💪_",
    "_Ciao! Sei qui per caso o perché tutti gli altri gruppi ti hanno bannato? 🚫_",
    "_Benvenuto! Il nostro gruppo è come un bonsai: richiede cure costanti e nessuno sa davvero come si fa 🌱_",
    "_Eccolo! Il membro che aspettavamo per completare il rituale dell'invocazione... scherzo (forse) 🔮_",
    "_Benvenuto! Sei il pezzo mancante del puzzle che nessuno sapeva mancasse 🧩_",
    "_Ciao! Sei pronto a diventare la nostra nuova vittima... ehm, amico? 👋_",
    "_Benvenuto! Qui siamo tutti normali... fino a prova contraria 🕵️_",
    "_Salve! Hai portato il tuo senso dell'umorismo? È obbligatorio qui 😂_",
    "_Benvenuto! Sei più un tipo da 'ciao a tutti' o da entrata in silenzio e osservazione? 🕶️_",
    "_Eccoti! Sapevi che il 97,3% delle statisticie sono inventate sul momento? 📊_",
    "_Benvenuto! Sei qui per la riunione degli Anonymous? Sbagliato gruppo, qui siamo dei noob 🖥️_",
    "_Ciao nuovo! Sei pronto a scoprire che la tua vita era più tranquilla prima di entrare qui? 🌪️_",
    "_Benvenuto! Il nostro gruppo è come un reality show, ma senza premio finale 🎥_",
    "_Salve! Hai già letto il manuale di sopravvivenza? No? Nessun problema, non esiste 📖_",
    "_Benvenuto! Sei l'eroe di cui non sapevamo di aver bisogno 🦸_",
    "_Ehilà! Sei qui per il corso di come fingere di lavorare mentre si chatta? 💼_",
    "_Benvenuto! Abbiamo già preparato il tuo certificato di 'Persona con troppi gruppi WhatsApp' 🏆_",
    "_Ciao! Sei più un tipo da 'leggo tutto' o da 'notifiche? quali notifiche?' 📱_",
    "_Benvenuto! Sei appena stato nominato Ministro delle Cose Inutili di questo gruppo 🎩_",
    "_Salve! Hai già preparato la scusa per quando ti chiederanno perché non rispondi? 🤥_",
    "_Benvenuto! Sei qui per caso o perché hai cliccato sul link sbagliato? 🔗_",
    "_Eccoti! Pronto a diventare famoso nei nostri screenshot fuori contesto? 📸_",
    "_Benvenuto! Il tuo livello di produttività è destinato a calare drasticamente da ora 📉_",
    "_Ciao nuovo! Sei qui per la riunione degli ex-membri? Aspetta... 🤔_",
    "_Benvenuto! Abbiamo appena scommesso su quanto durerai nel gruppo 🎰_",
    "_Salve! Sei più un tipo da 'rispondo subito' o da 'visto 3 giorni dopo'? ⌛_",
    "_Benvenuto! Sei il nostro esperimento sociale numero #384, buona fortuna! 🧪_",
    "_Eccolo! Il membro che completerà la nostra collezione di personalità strane 🎪_",
    "_Benvenuto! Qui dentro siamo tutti un po' pazzi, ma in modo carino... più o meno 🤪_",
    "_Ciao! Sei pronto a scoprire che la tua batteria non durerà mai più un giorno intero? 🔋_",
    "_Benvenuto! Sei entrato nel gruppo segreto che tutti sanno che esiste 🤐_",
    "_Salve! Hai già preparato la tua maschera per il ballo in maschera virtuale? 🎭_",
    "_Benvenuto! Sei più un tipo da 'scrivo poco ma significativo' o da 'spammo fino al ban'? 💣_",
    "_Eccoti! Sei qui per il corso accelerato 'Come sopravvivere a questo gruppo'? 📚_",
    "_Benvenuto! Abbiamo biscotti (virtuali) e problemi (reali) 🍪_",
    "_Ciao nuovo! Sei pronto a diventare parte del problema invece che della soluzione? 💡_",
    "_Benvenuto! Il nostro gruppo è come un treno: non sai dove va ma il viaggio è divertente 🚂_",
    "_Salve! Hai portato il tuo senso dell'umorismo? Senza non sopravviverai qui 😆_",
    "_Benvenuto! Sei l'ultimo pezzo del nostro esperimento sociale 🧩_",
    "_Ehilà! Sei qui per la protesta contro i messaggi vocali lunghi? 🎤_",
    "_Benvenuto! Abbiamo già preparato il tuo posto nella sezione 'membri strani' 🪑_",
    "_Ciao! Sei più un tipo da 'leggo tutto' o da 'scorro veloce e metto like a caso'? 👍_",
    "_Benvenuto! Sei appena stato nominato Vice Presidente delle Cose Inutili 🏛️_",
    "_Salve! Hai già imparato a ignorare le notifiche o sei ancora un principiante? 🔕_",
    "_Benvenuto! Il nostro gruppo è come un film: trama confusa ma personaggi interessanti 🎬_",
    "_Eccoti! Sei qui per il torneo di invio di gif più inappropriate? 🏆_",
    "_Benvenuto! Sei più un tipo da 'buongiornissimo' o da 'che schifo la mattina'? 🌅_",
    "_Ciao nuovo! Sei pronto a scoprire che la tua vita era più semplice prima di entrare qui? 🌀_",
    "_Benvenuto! Abbiamo già iniziato a parlare di te nelle tue spalle... virtuali 👥_",
    "_Salve! Hai portato il tuo certificato di resistenza allo spam? 📜_",
    "_Benvenuto! Sei l'elemento casuale che renderà questo gruppo ancora più imprevedibile 🎲_",
    "_Eccolo! Il membro che ci mancava per completare la squadra dei perdenti... ehm, vincenti! 🏅_",
    "_Benvenuto! Qui dentro la follia è obbligatoria e la sanità mentale opzionale 🧠_",
    "_Ciao! Sei pronto a diventare la nostra nuova fonte di gossip? 👂_",
    "_Benvenuto! Sei più un tipo da 'scrivo tantissimo' o da 'leggo e basta'? 📝_",
    "_Salve! Hai già preparato la scusa per quando ti chiederemo perché non parli mai? 🤐_",
    "_Benvenuto! Il nostro gruppo è come un'onda: a volte ti solleva, a volte ti travolge 🌊_",
    "_Eccoti! Sei qui per il workshop 'Come perdere tempo in modo produttivo'? ⏳_",
    "_Benvenuto! Abbiamo già iniziato a scommettere su quale sarà il tuo primo messaggio 🎰_",
    "_Ciao nuovo! Sei pronto a scoprire che la tua batteria non durerà mai più come prima? 🔌_",
    "_Benvenuto! Sei l'ultimo arrivato, quindi secondo la tradizione paghi da bere a tutti... virtualmente 🍻_",
    "_Salve! Hai già imparato a ignorare le discussioni politiche o sei ancora un novellino? 🗳️_",
    "_Benvenuto! Il nostro gruppo è come un libro: alcune pagine sono interessanti, altre... beh 📘_",
    "_Ehilà! Sei qui per il corso 'Come fingere di seguire la conversazione'? 🎓_",
    "_Benvenuto! Sei più un tipo da 'rispondo a tutti' o da 'leggo e ignoro'? 👀_",
    "_Ciao! Sei pronto a diventare il nostro nuovo capro espiatorio? 🐐_",
    "_Benvenuto! Abbiamo biscotti (finti) e drama (reale) 🎭_",
    "_Salve! Hai portato il tuo senso dell'umorismo? È obbligatorio per sopravvivere qui 😜_",
    "_Benvenuto! Sei l'elemento casuale che renderà questo gruppo ancora più folle 🃏_",
    "_Eccoti! Sei qui per la riunione degli ex-membri felici? Aspetta... 🤨_",
    "_Benvenuto! Il nostro gruppo è come un labirinto: una volta dentro non sai più come uscire 🏰_",
    "_Ciao nuovo! Sei pronto a scoprire che la tua produttività è appena crollata? 📉_",
    "_Benvenuto! Sei più un tipo da 'partecipo attivamente' o da 'osservo in silenzio'? 🕵️_",
    "_Salve! Hai già preparato la tua maschera per il ballo in maschera digitale? 🥸_",
    "_Benvenuto! Abbiamo già iniziato a parlare di te... in modo misterioso 👻_",
    "_Eccolo! Il membro che completerà la nostra collezione di personalità bizzarre 🎭_",
    "_Benvenuto! Qui dentro la normalità è fuori luogo e la follia è di casa 🏠_",
    "_Ciao! Sei pronto a diventare la nostra nuova fonte di meme? 🖼️_",
    "_Benvenuto! Sei più un tipo da 'buonanotte' o da 'messaggi alle 3 di notte'? 🌃_",
    "_Salve! Hai portato il tuo certificato di resistenza allo spam? È fondamentale qui 🛡️_",
    "_Benvenuto! Il nostro gruppo è come un romanzo: alcune parti sono noiose, altre... beh 📖_",
    "_Eccoti! Sei qui per il workshop 'Come perdere tempo con stile'? 💃_",
    "_Benvenuto! Abbiamo già scommesso su quanto durerai prima di silenziare il gruppo 🎲_",
    "_Ciao nuovo! Sei pronto a scoprire che la tua sanità mentale è in pericolo? 🚨_",
    "_Benvenuto! Sei l'ultimo arrivato, quindi secondo la tradizione paghi la pizza virtuale 🍕"
];

// Array motivi di addio
export const motiviAddio = [
  "_ha deciso di unirsi a un monastero digitale dove non si può usare WhatsApp 🧘_",
    "_è stato assunto come tester professionista di divani (deve stare sdraiato 8 ore al giorno) 🛋️_",
    "_ha vinto un concorso per diventare l'ambasciatore mondiale della noia 🏆_",
    "_sta seguendo il suo sogno di diventare un cercatore di funghi magici 🍄_",
    "_ha scoperto che la vita esiste fuori da WhatsApp ed è andato a verificare 🌍_",
    "_è stato reclutato dalla CIA per una missione segreta di monitoraggio dei gruppi WhatsApp 🕵️_",
    "_ha deciso di dedicarsi alla coltivazione di cactus emotivi 🌵_",
    "_è diventato un influencer di silenzi imbarazzanti 🤫_",
    "_sta scrivendo un libro intitolato 'Come sopravvivere a questo gruppo (e fallire miseramente)' 📚_",
    "_ha trovato un telefono Nokia 3310 e non riesce più a tornare alla tecnologia moderna 📱_",
    "_è partito per un viaggio spirituale alla ricerca del messaggio perfetto da inviare ✨_",
    "_ha deciso di diventare un eremita digitale nella foresta di Wifi-zero 🌲_",
    "_è stato assunto come guardiano notturno di un museo di emoji 🏛️_",
    "_sta seguendo un corso intensivo per diventare maestro di cerimonie di addii di gruppo 🎓_",
    "_ha scoperto che era l'unico normale nel gruppo ed è scappato terrorizzato 😱_",
    "_è diventato un cacciatore professionista di notifiche perse 🔍_",
    "_ha deciso di aprire una scuola per insegnare come uscire dai gruppi con stile 🎩_",
    "_è stato rapito da una setta che crede che i messaggi vocali siano il male assoluto 🎤_",
    "_sta testando un nuovo stile di vita chiamato 'senza gruppi WhatsApp' 🧪_",
    "_ha vinto un viaggio tutto pagato per l'isola di 'Nonesistewhatsapp' 🏝️_",
    "_è diventato il presidente del fan club di chi esce dai gruppi 🏅_",
    "_ha deciso di dedicarsi alla meditazione trascendentale su 'perché ho cliccato quel link' 🧘_",
    "_è stato assunto come esperto di uscite drammatiche da gruppi social 🎭_",
    "_sta scrivendo la colonna sonora del suo addio al gruppo 🎵_",
    "_ha scoperto che era un NPC in un simulatore di gruppi WhatsApp e si è autodistrutto 🤖_",
    "_è partito per un safari fotografico alla ricerca del rarissimo 'Utente Che Legge Le Regole' 📸_",
    "_ha deciso di diventare un collezionista di notifiche non lette 🔔_",
    "_è stato scelto come protagonista del nuovo reality 'Sopravvissuto: Senza WhatsApp' 📺_",
    "_sta seguendo un master in 'Come spiegare ai nipoti cosa erano i gruppi WhatsApp' 👴_",
    "_ha vinto il premio per 'Uscita più creativa da un gruppo' e se n'è andato per ritirarlo 🏆_",
    "_è diventato un ricercatore di messaggi persi nel cyberspazio 🚀_",
    "_ha deciso di aprire un bed & breakfast per ex-membri di gruppi WhatsApp 🛏️_",
    "_è stato assunto come stuntman per uscite spettacolari da gruppi social 🤸_",
    "_sta scrivendo un manuale di sopravvivenza per chi vuole uscire dai gruppi 📖_",
    "_ha scoperto che era l'unico a non aver silenziato il gruppo ed è impazzito 🤯_",
    "_è partito per un pellegrinaggio digitale al santuario di 'Mai Più Notifiche' 🛐_",
    "_ha deciso di diventare un artista di performance che esce da gruppi in modo creativo 🎨_",
    "_è stato reclutato per una missione segreta di sabotaggio di gruppi noiosi 🕵️_",
    "_sta testando un nuovo social network chiamato 'SenzaGruppi' 💻_",
    "_ha vinto una causa contro WhatsApp per danni da troppe notifiche e se n'è andato con i soldi 💸_",
    "_è diventato un filosofo specializzato in 'Perché siamo entrati in questo gruppo?' 🧠_",
    "_ha deciso di aprire un museo delle conversazioni dimenticate 🏛️_",
    "_è stato assunto come critico professionista di messaggi di addio 📝_",
    "_sta scrivendo un poema epico sulla sua uscita dal gruppo ✍️_",
    "_ha scoperto che era l'ultimo a sapere che il gruppo era morto da mesi 💀_",
    "_è partito per un viaggio nel tempo per impedire a se stesso di entrare nel gruppo ⏳_",
    "_ha deciso di diventare un giardiniere digitale e coltivare piante invece di chat 🌱_",
    "_è stato scelto come protagonista del film 'L'Uomo Che Uscì Dal Gruppo' 🎬_",
    "_sta seguendo un corso accelerato su 'Come dimenticare tutto quello letto in questo gruppo' 🧠_",
    "_ha vinto il premio Nobel per la pace dopo esser uscito da tutti i gruppi WhatsApp 🏅_",
    "_è diventato un esploratore di chat abbandonate 🗺️_",
    "_ha deciso di aprire una spa per disintossicazione da gruppi social 💆_",
    "_è stato assunto come detective per ritrovare il senso originario delle conversazioni perse 🔍_",
    "_sta scrivendo un diario segreto sulle sue vere ragioni per uscire dal gruppo 📓_",
    "_ha scoperto che era un esperimento sociale e ha smesso di partecipare 🧪_",
    "_è partito per un ritiro spirituale chiamato 'Trovare la pace dopo il gruppo' ☮️_",
    "_ha deciso di diventare un archeologo digitale che studia vecchie chat 🏺_",
    "_è stato scelto come testimonial per una campagna contro l'abuso di gruppi WhatsApp 📢_",
    "_sta testando un nuovo stile di vita chiamato 'Conversazioni Reali' 👥_",
    "_ha vinto un viaggio per il villaggio di 'NienteInternet' e ha accettato con gioia 🚣_",
    "_è diventato un maestro di cerimonie per funerali di gruppi WhatsApp ⚰️_",
    "_ha deciso di aprire un ristorante per ex-membri chiamato 'Ultima Cena Nel Gruppo' 🍽️_",
    "_è stato assunto come consulente per uscite eleganti da situazioni social imbarazzanti 💼_",
    "_sta scrivendo un thriller intitolato 'Il Codice Del Gruppo Perduto' 📖_",
    "_ha scoperto che era l'unico a non aver silenziato le notifiche ed è fuggito urlando 🏃_",
    "_è partito per un'avventura alla ricerca del mitico 'Gruppo Perfetto' che non esiste 🗺️_",
    "_ha deciso di diventare un monaco votato al silenzio digitale dopo questo gruppo 🤫_",
    "_è stato reclutato da un'organizzazione segreta che combatte lo spam nei gruppi 🦸_",
    "_sta testando un nuovo concetto chiamato 'Vita Reale' che sembra promettente 🌎_",
    "_ha vinto un soggiorno in una cabina senza segnale e ha pianto di gioia 🛖_",
    "_è diventato un critico d'arte specializzato in screenshot di conversazioni 🎨_",
    "_ha deciso di aprire un santuario per messaggi non letti 🛐_",
    "_è stato assunto come stuntman digitale per uscite spettacolari da chat 💥_",
    "_sta scrivendo un'autobiografia intitolata 'La Mia Fuga Dal Gruppo' 📘_",
    "_ha scoperto che era l'unico a rispondere seriamente ai messaggi e si è sentito tradito 🎭_",
    "_è partito per un viaggio alla ricerca del leggendario 'Gruppo Senza Spam' 🌈_",
    "_ha deciso di diventare un agricoltore di emoji rare dopo questa esperienza 🌾_",
    "_è stato scelto come protagonista del documentario 'Addio, Mio Gruppo' 🎥_",
    "_sta seguendo un master in 'Come spiegare ai tuoi genitori cosa è un gruppo WhatsApp' 👨‍👦_",
    "_ha vinto il premio per 'Uscita più misteriosa da un gruppo' e ha lasciato indizi falsi 🕵️_",
    "_è diventato un esploratore urbano di chat abbandonate 🏙️_",
    "_ha deciso di aprire un bed & breakfast per anime perse nei gruppi WhatsApp 🛌_",
    "_è stato assunto come ghostwriter per messaggi di addio convincenti 👻_",
    "_sta scrivendo un trattato filosofico su 'L'Essere e il Non Essere in un Gruppo' 📜_",
    "_ha scoperto che era l'unico a non usare meme e si è sentito inadeguato 😔_",
    "_è partito per un pellegrinaggio digitale al tempio di 'Mai Più Notifiche' 🛐_",
    "_ha deciso di diventare un artista concettuale che esce da gruppi in modo creativo 🎭_",
    "_è stato reclutato per una missione segreta di pulizia di gruppi inattivi 🧹_",
    "_sta testando un nuovo social network chiamato 'AntiGruppi' dove non ci sono gruppi 🖥️_",
    "_ha vinto una causa per danni da overdose di messaggi e se n'è andato con un assegno 💰_",
    "_è diventato un filosofo digitale specializzato in 'Perché siamo usciti da quel gruppo?' 🤔_",
    "_ha deciso di aprire un museo delle notifiche rimosse con noncuranza 🏛️_",
    "_è stato assunto come critico professionista di dinamiche di gruppo social 📊_",
    "_sta scrivendo un poema epico sulla sua epica fuga dal gruppo ✍️_",
    "_ha scoperto che era l'ultimo membro attivo e ha spento la luce uscendo 💡_",
    "_è partito per un viaggio nel metaverso per trovare un gruppo migliore 🕶️_",
    "_ha deciso di diventare un giardiniere digitale e coltivare silenzi invece di chat 🤫_",
    "_è stato scelto come protagonista del film 'Fuga Dal Gruppo WhatsApp' 🎬_",
    "_sta seguendo un corso accelerato su 'Come dimenticare le conversazioni viste qui' 🧠_",
    "_ha vinto il premio per 'Uscita più poetica da un gruppo' con un sonetto d'addio 🎭_",
    "_è diventato un archeologo digitale che studia le rovine di gruppi abbandonati ⚱️_",
    "_ha deciso di aprire una spa per disintossicazione da notifiche da gruppo 💆_",
    "_è stato assunto come detective per ritrovare il senso originario perso nelle chat 🔎_",
    "_sta scrivendo un diario segreto intitolato 'Le Vere Ragioni Della Mia Fuga' 📔_",
    "_ha scoperto che era un test psicologico e ha rifiutato di continuare 🧪_",
    "_è partito per un ritiro spirituale chiamato 'Trovare la pace dopo le notifiche' ☯️_",
    "si trova all'ospedale 🏥",
    "ha deciso di esplorare il mondo 🌍",
    "ha vinto la lotteria e si è trasferito 💸",
    "ha dimenticato il caricabatterie e non potra piu scrivere🔌",
    "ha trovato il vero amore (o almeno così dice) 💖",
    "è stato rapito dagli alieni 👽",
    "ha deciso di prendersi una pausa dai social 📵",
    "sta scrivendo un libro sulle esperienze nei gruppi WhatsApp 📖",
    "è andato a caccia di unicorni 🦄",
    "ha scoperto una nuova passione per il giardinaggio 🌱",
    "si sta allenando per diventare un ninja 🥷",
    "ha deciso di unirsi a un circo e ora fa il paiaccio 🎪",
    "sta inseguendo il sogno di diventare un astronauta 🚀",
    "ha aperto una gelateria tropicale in guatemala🍦",
    "ha iniziato a studiare la lingua delle balene 🐋",
    "è andato a cercare il tesoro perduto dei pirati 🏴‍☠️",
    "è stato ingaggiato come investigatore segreto 🕵️‍♂️",
    "ha scelto di vivere in una grotta per diventare uno sciamano 🪄",
    "ha trovato un portale per un'altra dimensione 🌌",
    "era un infiltrato della polizia, ha raccolto le prove che gli servivano 🚔",
    "veniva bullizzato dagli altri utenti 🔞",
    "sua madre ha aperto WhatsApp e ha visto cosa mandate\n...lo sta ancora cinghiando 🔞",
    "ha cagato nel puzzo 🕳️",
    "e' affogato 🏊🏻‍♀️",
    "e' stato swattato in casa 👮🏻",
    "ha detto la N word ed e stato cancellato dai social 📱",
    "ha ingerito troppi peni",
    "e' stato beccatto a scaccolarsi in pubblico, la sua immagine e' stata rovinata🤳🏻",
    "sta girando un film su come diventare ricchi con WhatsApp 🤑",
    // Nuovi motivi di addio
    "ha scoperto che la Terra è piatta ed è andato a cercare il bordo 🌎",
    "è stato assunto da Netflix per una nuova serie su gente che abbandona i gruppi 🎬",
    "ha trovato una lampada magica e il suo primo desiderio è stato uscire da qui 🧞",
    "la sua copertura come spia internazionale è stata compromessa 🕴️",
    "ha visto i nostri meme e ha subito danni cerebrali permanenti 🧠",
    "è stato scelto per partecipare al Grande Fratello VIP 📺",
    "ha realizzato di essere troppo intelligente per questo gruppo 🎓",
    "sta costruendo un bunker per l'apocalisse zombie 🧟",
    "ha deciso di unirsi a una comune hippie e rinunciare alla tecnologia 🌸",
    "è caduto nel water e non riesce più a uscire 🚽",
    "ha scoperto che il suo gatto sa usare WhatsApp ed era lui a scrivere tutto il tempo 🐱",
    "è stato risucchiato dal suo aspirapolvere 🧹",
    "si è trasferito in Antartide per studiare i pinguini 🐧",
    "ha finalmente trovato il coraggio di confessare i suoi sentimenti alla crush... ed è stato rifiutato così malamente che ora è in terapia 💔",
    "è entrato accidentalmente in un programma protezione testimoni 🛡️",
    "ha scoperto che il 5G gli stava controllando la mente ed ha gettato il telefono nel fiume 📱",
    "è stato chiamato da Elon Musk per una missione su Marte 👨‍🚀",
    "si è perso nel triangolo delle Bermuda cercando il Wi-Fi gratuito ⚠️",
    "è finito in prigione per crimini contro l'umanità (ha messo il ketchup sulla pasta) 🍝",
    "è stato ipnotizzato da un video di TikTok e ora crede di essere una gallina 🐔",
    "ha perso il telefono nel bidone della spazzatura e ora è in viaggio verso la discarica 🗑️",
    "ha vinto un concorso per diventare un eremita professionale 🏕️",
    "è stato chiamato d'urgenza per sostituire Batman 🦇",
    "ha deciso di seguire il coniglio bianco nella tana... non abbiamo più sue notizie 🐇",
    "il suo telefono è esploso dopo aver ricevuto 1000 notifiche in un minuto 💥",
    "ha deciso di inseguire il suo sogno di diventare un influencer di sassi 🪨",
    "è stato assunto come assaggiatore professionale di gelati 🍨",
    "è in fuga dalla mafia dei panda 🐼",
    "ha scoperto che il suo telefono era posseduto da un demone e ora sta facendo un esorcismo 👹",
    "è andato a comprare le sigarette... non tornerà mai più 🚬",
    "ha aperto un portale per gli inferi scrollando troppo a lungo su Instagram 🔥",
    "è stato reclutato da Anonymous per hackerare il frigorifero di Putin 🥷",
    "gli è caduto il telefono nel gabinetto mentre faceva un selfie 📸",
    "ha trovato un vecchio mappamondo e sta cercando l'Atlantide con una bussola rotta 🧭",
    "ha vinto una causa contro Mark Zuckerberg e ora è proprietario di Meta 💼",
    "è diventato un monaco tibetano e ha fatto voto di silenzio digitale 🧘",
    "ha scoperto che era l'ultimo a sapere che questo gruppo fa schifo 💩",
    "sta cercando di costruire una macchina del tempo per tornare indietro e non entrare mai in questo gruppo ⏰",
    "è andato a un concerto e si è lanciato nel pubblico, ma nessuno l'ha preso 🎵",
    "è diventato una leggenda urbana dopo essere scomparso misteriosamente da questo gruppo 👻",
    "ha deciso di vivere come un personaggio di The Sims e ora è bloccato in piscina senza scala 🏊",
    "ha trovato la ricetta segreta della Coca-Cola e ora è in fuga 🥤",
    "si è iscritto a un corso per diventare domatore di unicorni 🦄",
    "ha cambiato identità dopo aver postato un meme troppo cringe 😬",
    "è stato scelto come volontario per testare i cibi per gatti 🐈",
    "è entrato in un programma di riabilitazione per dipendenza da emoji 😵‍💫",
    "è stato assunto come controfigura per film d'azione, ma al primo stunti si è rotto tutti gli arti 🦴",
    "ha deciso di diventare un pirata informatico ma ha confuso hacking con hackeraggio e ora naviga su una zattera nel Mediterraneo 🏴‍☠️",
    "è andato alla ricerca del leggendario Fungo Gigante dell'Amazzonia 🍄",
    "ha scoperto che era l'ultimo esemplare di una specie aliena e i suoi simili sono venuti a riprenderselo 👾",
    "è entrato in un armadio pensando di trovare Narnia ma ha trovato solo vecchi vestiti puzzolenti 🧥",
    "ha creduto nella pubblicità 'Diventa milionario in un giorno' e ora sta vendendo i reni sul mercato nero 💉",
    "ha deciso di farsi ibernare fino al 2077 per giocare a Cyberpunk senza bug 🧊",
    "è diventato vegano e ora passa le giornate a dire a tutti che è vegano 🥗",
    "è stato ricoverato per overdose di meme 🤣",
    "sta cercando di diventare una star di OnlyFans cucinando in pantofole 👣",
    "ha chiesto a ChatGPT di guidare la sua vita e ora vive in una grotta 🤖",
    "ha deciso di vivere come un pomodoro e ora trascorre le giornate al sole 🍅"
];
	export const motiviBentornato = [
      "ma riciao @user",
     "Bentornato @user Ci sei mancato! 💖",
    "Eccoti di nuovo qui  🎉",
    "Oh, guarda chi è tornato! @user  👀",
    " @user ha deciso di tornare tra noi! 🥳",
    "Ben tornato @user! Stavamo iniziando a preoccuparci 😌",
    " @user è riapparso come per magia! ✨",
    "E il prodigo @user ritorna! 🏠"  
];
/**
 * Ottiene un messaggio di benvenuto casuale
 * @returns {string} Frase di benvenuto casuale
 */
export function getBenvenutoRandom() {
    return frasiBenvenuto[Math.floor(Math.random() * frasiBenvenuto.length)];
}

export function getAddioRandom() {
    return motiviAddio[Math.floor(Math.random() * motiviAddio.length)];
}

export function getBentornatoRandom() {
    return motiviBentornato[Math.floor(Math.random() * motiviBentornato.length)];
}