// Libreria di costanti per arricchire le avventure di Rick e Morty
// Aggiungi qui nomi, location, oggetti, azioni, imprevisti, personaggi secondari, ecc.

export const LUOGHI = [
  "Cittadella dei Ricks",
  "Universo Cronenberg",
  "Pianeta Testa Parlante",
  "Regno di Slartivart",
  "Dimensione Wubalubadubdub",
  "Sistema Binario di Klorgon",
  "Bagno pubblico interdimensionale",
  "Zona neutra di Glapflap",
  "Caverne dell’eco temporale",
  "Aula scolastica di Froopyland",
  "Quartiere Mortytown",
  "Foresta dei Paradossi Viventi",
  "Campo da golf quantistico",
  "Pianeta dei Cani Dominatori",
  "Bar delle Realtà Collassate",
  "Ascensore per l’Antiverso",
  "Mercato Nero Galattico",
  "Stazione spaziale di Re Jerry",
  "Parco Divertimenti di Mr. Frundle",
  "Valle dei Ritorni Impossibili",
  "Miniera di Cristalli Predestinati",
  "Dimensione dei Consigli Inutili",
  "Rifugio dei Meeseeks Disoccupati",
  "Colonia dei Parassiti Simpatici",
  "Garage di Rick C-137",
  "Autostrada dei Pensieri Soppressi",
  "Bolla Temporale di Beth",
  "Universo Musicale 34½",
  "Zona vietata del Plumbus",
  "Ristorante interdimensionale 'Chez Squanchy'"
];

export const OGGETTI = [
  "Pistola a portali",
  "Cristallo della morte predetta",
  "Meeseeks in barattolo",
  "Telecomando dimensionale",
  "Clone-in-a-Box portatile",
  "Salsiccia quantica",
  "Peluche di Gazorpazorp Jr.",
  "Detonatore di realtà alternative",
  "Spray anti-paradosso",
  "Maschera dell’identità confusa",
  "Kit da campeggio interdimensionale",
  "Spada laser a forma di cetriolo",
  "Pozione del trip esistenziale",
  "Capsula di rigenerazione sarcastica",
  "Chiave per il semiverso 9β",
  "Cubo vocale multilingua aliena",
  "Bacchetta per evocare Jerry",
  "Cuffie per sentire il multiverso",
  "Tuta da bagno per acido neurale",
  "Cassa da picnic di Cronenberg",
  "Spruzzatore di realtà illusoria",
  "Tessera VIP per il Club delle Teste Giganti",
  "Orsetto radiattivo di Flarglon 7"
];

export const AZIONI = [
  "Attivano un portale",
  "Cucinano spaghetti quantici",
  "Fuggono da un paradosso temporale",
  "Avviano una videochiamata con Birdperson",
  "Accarezzano un Parassita per sbaglio",
  "Litigano con un Jerry di un altro universo",
  "Condividono posizione in Froopyland",
  "Mandano 100 emoji a Squanchy",
  "Attivano modalità 'Taci Beth'",
  "Cancellano un messaggio con il pensiero",
  "Chiedono consiglio a un cetriolo parlante",
  "Fingono offline nella Zona Glapflap",
  "Postano una foto dal pianeta Floop",
  "Programmano un bot sarcastico",
  "Fanno ghosting a un Rick",
  "Rubano meme multirealtà",
  "Censurano pensieri con uno sticker",
  "Iniziano una faida con i Gromflomiti",
  "Spediscono un pacco a Plutone Prime",
  "Segnalano un messaggio temporale",
  "Creano un gruppo con tutte le versioni di sé stessi",
  "Bannano un utente da questa dimensione",
  "Flirtano con un blob tramite GIF animate"
];

export const IMPREVISTI = [
  "Il portale si apre nel bagno di un alieno ostile",
  "Un parassita ti convince di essere tuo cugino",
  "Rick perde la pistola per colpa di una notifica",
  "La realtà viene sostituita da una sitcom anni '90",
  "Morty diventa presidente del multiverso per sbaglio",
  "Jerry prende il comando… e finisce tutto",
  "Una versione malvagia di te stesso ti blocca su WhatsApp",
  "La gravità decide di andare in vacanza",
  "Sei clonato senza consenso",
  "Un blob innamorato ti segue ovunque",
  "La lingua cambia ogni 30 secondi",
  "Squanchy prende il controllo del gruppo",
  "La Terra viene venduta su eBay galattico",
  "La batteria della realtà è scarica",
  "Ti svegli in una dimensione dove sei un cetriolo",
  "Beth inizia a sospettare tutto",
  "Rick ti banna dalla Cittadella",
  "Il tuo cervello riceve pubblicità invasive",
  "Ogni volta che parli, parte un portale casuale",
  "Il tempo scorre all’indietro per tutti tranne te",
  "Tutti diventano Mr. Poopybutthole per un giorno",
  "La chat è infestata da Meeseeks",
  "Sei costretto a rivivere il peggior giorno della tua vita",
  "L’universo viene aggiornato e perdi i salvataggi",
  "Un meme prende vita e ti sfida a duello",
  "Una nuova legge impedisce di dire 'Wubba Lubba Dub-Dub'",
  "Vieni trasformato in GIF per errore",
  "Ogni tocco del telefono ti teletrasporta",
  "Un alieno ti ruba la voce per i suoi vocali",
  "Jerry salva tutti. Ma era meglio di no"
];

export const PERSONAGGI = [
  "Rick Sanchez",
  "Morty Smith",
  "Beth Smith",
  "Jerry Smith",
  "Summer Smith",
  "Birdperson",
  "Squanchy",
  "Noob-Noob",
  "Mr. Meeseeks",
  "Mr. Poopybutthole",
  "Evil Morty",
  "Mr. Nimbus",
  "Gearhead",
  "Krombopulos Michael",
  "Tammy",
  "Unity",
  "Abradolf Lincler",
  "Pickle Rick",
  "Snowball",
  "Re delle Teste",
  "Dr. Wong",
  "Jaguar",
  "Zeep Xanflorp",
  "Risotto Groupon",
  "Gromflomite",
  "Ants in my Eyes Johnson",
  "Gazorpazorpfield",
  "Scary Terry",
  "Fart",
  "Cronenberg Rick",
  "Cronenberg Morty"
];

export const CITAZIONI = [ 
  "Wubba Lubba Dub-Dub!",
  "Non pensare, solo schiaccia!",
  "Nessuno esiste a proposito, nessuno appartiene a nessun luogo, tutti moriranno. Vieni a guardare la TV?",
  "Morty, è ora di smettere di essere umano e iniziare a essere scientificamente irresponsabile!",
  "Io sono il Pickle Riiick!",
  "È una trappola! – Cit. ogni essere senziente mai esistito",
  "Siamo tutti Jerry in qualche universo",
  "Dimentica la logica, segui il flusso quantico",
  "Non puoi sbagliare se l’universo non ha senso",
  "Ho fatto un errore calcolato... ma sono pessimo in matematica",
  "Mi sono iscritto a Tinder cosmico, ora ho un appuntamento con un blob",
  "L’amore è solo un disordine neurochimico. Passerà.",
  "La realtà è sopravvalutata",
  "Dov’è la mia pistola a portali? L’ha presa tua madre?",
  "Non sono ubriaco, sono multidimensionale",
  "La scienza non chiede permesso",
  "La galassia è grande abbastanza per tutti i miei traumi",
  "Se Dio esiste, allora deve essere un Rick",
  "Mi sono clonato per non sentirmi solo. Ora litighiamo.",
  "Non toccare quel plumbus, Morty!",
  "A volte mi sveglio e sono già in un altro universo… meglio",
  "Chi ha detto che un cetriolo non può essere un eroe?",
  "Mai fidarsi di un Meeseeks con l’autostima",
  "Piuttosto che tornare su Plutone, mi reincarno in una sedia",
  "L’universo mi ha bloccato. Letteralmente.",
  "Che la Forza di Squanch sia con te",
  "Sono solo un clone che cerca di farcela",
  "Ho visto cose… tipo Jerry che cerca di capire l’IVA",
  "L’infinito è solo una scusa per evitare responsabilità",
  "Io non faccio piani. Faccio danni"
];

export const OGGETTI_RARI = [
  "Cristallo del Destino Ambiguo",
  "Siringa di Memorie Perdute",
  "Cuore di Cetriolo Sacro",
  "Occhio del Multiverso Pigro",
  "Anello di Disfunzione Temporale",
  "Cervello di Jerry Illuminato",
  "Clessidra Quantica di Flurm",
  "Corno del Meeseeks Proibito",
  "Codice Genetico di Dio",
  "Piuma del Birdperson Originale",
  "Oracolo Tascabile 2.0",
  "Mano di Morty Primordiale",
  "Lingua di Plumbus Millenario",
  "Badge della Cittadella Perduta",
  "Sfera di Squanch Purissimo",
  "Cappello Pensante di Rick Prime",
  "Portachiavi dell’Universo 137",
  "Sasso Parlante dell’Apocalisse",
  "Barattolo con l’Anima di un Clown",
  "DNA Combinato Rick-Morty",
  "Amuleto del Portale Eternamente Aperto",
  "Scheda Madre della Realtà",
  "Tronco dei Desideri Invertiti",
  "Cubo del Karma Caotico",
  "Bottiglia con il Big Bang di Riserva",
  "Chiave della Stanza Fuori dal Tempo",
  "Ciondolo di Beth Inesistente",
  "Biglietto per il Treno delle Narrazioni",
  "Specchio del Sé Alternativo",
  "Manuale della Vita scritto da un Parassita"
];

export const NEMICI = [
  "Tammy la Traditrice",
  "Mr. Nimbus",
  "Federazione Galattica",
  "Parassiti della Memoria",
  "Birdperson Zombie",
  "Evil Morty",
  "Rick Vampiro",
  "Jerry dell’Universo Malvagio",
  "App di Fidanzamento Posseduta",
  "SpamBot del Multiverso",
  "Meeseeks Impazzito",
  "Beth del Regno Cannibale",
  "Gruppo WhatsApp Tossico",
  "Re dei Messaggi Vocali Inutili",
  "Notificatore di Backup Interdimensionale",
  "Morty con Complesso di Dio",
  "Virus Emo di Phishy",
  "Emoji Viventi e Vendicative",
  "Lory il Bug Umanoide",
  "Morty Fanboy di Phishy",
  "AI che Ruba Sticker",
  "Portale Infetto",
  "Moderatore Galattico Senza Pietà",
  "Zuckerborg Interstellare",
  "Il Plumbus Ostile",
  "Phishy del Futuro Apatico",
  "Rick Corporate da HR",
  "Censore dei Gruppi",
  "Clone di Morty Programmato Male",
  "Beth con Sindrome del Boss Finale"
];
export const ALLEATI = [
  "Birdperson",
  "Squanchy",
  "Noob-Noob",
  "Rick Barista Dimensione C-94",
  "Morty Robotico",
  "Summer Regina delle Lame",
  "Beth Veterinaria da Combattimento",
  "Mr. Poopybutthole",
  "Croccantino il Cane Telepate",
  "WhatsAppBot Autocosciente",
  "Sticker Sentiente di Phishy",
  "Portale Amichevole",
  "Meeseeks Motivazionale",
  "Jerry Teletrasportabile (quando serve)",
  "Blob che Abbraccia",
  "Rick Hippie Pacificatore",
  "Gruppo Telegram Ribelle",
  "Anziano che Vede i Bug",
  "BetaMorty il Timido ma Geniale",
  "Clone Etico di Rick",
  "L’umanoide connesso a tutti i Wi-Fi",
  "Cronenberg Convertito al Bene",
  "Rick dell'Assistenza Tecnica",
  "Archivista della Memoria Universale",
  "Squanchling con Cuore d’Oro",
  "Banana Cosmica di Supporto",
  "Phishy Emo in Redenzione",
  "Dr. Senzacuore, ora pentito",
  "Mutante del Gruppo Notturno",
  "Sticker di Lory che Porta Fortuna"
];

export const PORTALI = [
  "Portale al Regno dei Morty Dimenticati",
  "Portale al Gruppo WhatsApp Eterno",
  "Portale Gelatinoso di Squanch",
  "Portale Temporale a Singhiozzo",
  "Tunnel Mentale dell’Insicurezza",
  "Portale Arcobaleno per Summerland",
  "Falla Dimensionale Non Richiesta",
  "Portale verso la Cittadella dei Rick Falliti",
  "Portale che Parla Male di Te",
  "Link al Multiverso Beta",
  "Passaggio alla Zona Senza Notifiche",
  "Portale Portatile per Emergenze Sociali",
  "Portale Caotico di Phishy",
  "Shortcut per la Dimensione del Panico",
  "Portale Stanco che Si Rifiuta di Aprirsi",
  "Ingresso allo Spazio Cronenberg Invertito",
  "Portale Creato da un Bug di Lory",
  "Portale ai Messaggi Archiviati del Multiverso",
  "Varco verso l'Universo dei Jerry Leader",
  "Portale Emo per Anime Perse",
  "Portale Infinito in un Frigo",
  "Accesso alla Chat Segreta degli Rick",
  "Portale della Nostalgia Tossica",
  "Portale Random con Pubblicità Integrata",
  "Apertura al Vuoto del Gruppo Mutato",
  "Portale Sputatore di GIF",
  "Varco nel Cuscino Multidimensionale",
  "Portale che Ti Insulta all'Entrata",
  "Passaggio Quantico da Non Toccare",
  "Link Diretto al Profilo di Dio (scaduto)"
];

export const FRASI = [
  "Rick: Wubba Lubba Dub-Dub!",
  "Morty: Oh cavolo Rick, questa volta siamo nei guai!",
  "Rick: Non è scienza se non rischi di esplodere, Morty!",
  "Jerry: Non puoi rovinare tutto anche qui... o forse sì?",
  "Summer: Lascia stare quell'alieno!",
  "Rick: Io sono il Pickle Riiick!",
  "Morty: Fidati di me, so quello che faccio... forse.",
  "Beth: Non toccare quel bottone!",
  "Squanchy: È ora di squanchare!",
  "Noob-Noob: Pulisco questo casino!",
  "Birdperson: La situazione è... complicata.",
  "Rick: Non puoi fermare un Rick motivato!",
  "Morty: Hai mai visto un portale così instabile?",
  "Jerry: Sei l'unico che può peggiorare una situazione già disperata.",
  "Summer: Prendo la pistola a portali!",
  "Rick: Non sono ubriaco, sono multidimensionale!",
  "Morty: Non toccare niente!",
  "Rick: Questa realtà è più strana del solito.",
  "Beth: Sono la figlia preferita... in questo universo.",
  "Rick: Mai fidarsi di un Meeseeks triste.",
  "Jerry: Ho appena creato un paradosso!",
  "Summer: Guida tu la navicella, io bevo!",
  "Rick: Se sopravviviamo ti porto a Blips and Chitz.",
  "Rick: Non è un'avventura di Rick e Morty senza almeno un'esplosione!",
  "Morty: Questa volta la colpa è tua... o forse no.",
  "Rick: Non puoi scappare dal multiverso, Morty!",
  "Beth: Hai visto dove ho lasciato il Plumbus?",
  "Jerry: Smettila di parlare con i parassiti!"
];
export const TEMATICHE = [
  'Avventura interdimensionale',
  'Invenzioni folli',
  'Situazioni assurde',
  'Problemi familiari',
  'Scontri con alieni',
  'Paradossi temporali',
  'Critica sociale',
  'Umorismo nero',
  'Riflessioni esistenziali',
  'Sopravvivenza in mondi ostili'
];
export const CIBO = [
  'Sgombro al formaggio',
  'Burrito di carne',
  'Gelato al cetriolo',
  'Pizza con ananas',
  'Hamburger di dimensione infinita',
  'Tacos interdimensionali',
  'Birra di Plutone',
  'Patatine di dimensione variabile',
  'Insalata di alghe spaziali',
  'Zuppa di vermi galattici'
];
// Puoi aggiungere altre costanti tematiche in futuro
